# Generated by Django 6.0.1 on 2026-01-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagepromotion',
            name='deduction_strategy',
            field=models.CharField(choices=[('fixed_only', 'Deduct Fixed Items Only'), ('selected_only', 'Deduct Customer Selection Only'), ('all_components', 'Deduct All Components')], default='all_components', help_text='How inventory should be deducted for this package', max_length=20),
        ),
    ]
