# Generated by Django 5.2.10 on 2026-01-30 00:00

from django.db import migrations


def migrate_promotion_product_ids(apps, schema_editor):
    """Update promotions product-related FKs/M2M columns to UUID using core_product.legacy_id."""
    # Promotion FK columns
    schema_editor.execute("ALTER TABLE promotions_promotion ADD COLUMN IF NOT EXISTS get_product_id_new uuid;")
    schema_editor.execute("ALTER TABLE promotions_promotion ADD COLUMN IF NOT EXISTS required_product_id_new uuid;")
    schema_editor.execute("ALTER TABLE promotions_promotion ADD COLUMN IF NOT EXISTS upsell_product_id_new uuid;")

    schema_editor.execute(
        """UPDATE promotions_promotion p
           SET get_product_id_new = cp.id
           FROM core_product cp
           WHERE p.get_product_id::text = cp.legacy_id::text;"""
    )
    schema_editor.execute(
        """UPDATE promotions_promotion p
           SET required_product_id_new = cp.id
           FROM core_product cp
           WHERE p.required_product_id::text = cp.legacy_id::text;"""
    )
    schema_editor.execute(
        """UPDATE promotions_promotion p
           SET upsell_product_id_new = cp.id
           FROM core_product cp
           WHERE p.upsell_product_id::text = cp.legacy_id::text;"""
    )

    schema_editor.execute("ALTER TABLE promotions_promotion DROP COLUMN get_product_id CASCADE;")
    schema_editor.execute("ALTER TABLE promotions_promotion DROP COLUMN required_product_id CASCADE;")
    schema_editor.execute("ALTER TABLE promotions_promotion DROP COLUMN upsell_product_id CASCADE;")

    schema_editor.execute("ALTER TABLE promotions_promotion RENAME COLUMN get_product_id_new TO get_product_id;")
    schema_editor.execute("ALTER TABLE promotions_promotion RENAME COLUMN required_product_id_new TO required_product_id;")
    schema_editor.execute("ALTER TABLE promotions_promotion RENAME COLUMN upsell_product_id_new TO upsell_product_id;")

    schema_editor.execute(
        """ALTER TABLE promotions_promotion
           ADD CONSTRAINT promotions_promotion_get_product_id_fk
           FOREIGN KEY (get_product_id) REFERENCES core_product(id) ON DELETE SET NULL;"""
    )
    schema_editor.execute(
        """ALTER TABLE promotions_promotion
           ADD CONSTRAINT promotions_promotion_required_product_id_fk
           FOREIGN KEY (required_product_id) REFERENCES core_product(id) ON DELETE SET NULL;"""
    )
    schema_editor.execute(
        """ALTER TABLE promotions_promotion
           ADD CONSTRAINT promotions_promotion_upsell_product_id_fk
           FOREIGN KEY (upsell_product_id) REFERENCES core_product(id) ON DELETE SET NULL;"""
    )

    # PromotionTier.free_product
    schema_editor.execute("ALTER TABLE promotions_promotiontier ADD COLUMN IF NOT EXISTS free_product_id_new uuid;")
    schema_editor.execute(
        """UPDATE promotions_promotiontier pt
           SET free_product_id_new = cp.id
           FROM core_product cp
           WHERE pt.free_product_id::text = cp.legacy_id::text;"""
    )
    schema_editor.execute("ALTER TABLE promotions_promotiontier DROP COLUMN free_product_id CASCADE;")
    schema_editor.execute("ALTER TABLE promotions_promotiontier RENAME COLUMN free_product_id_new TO free_product_id;")
    schema_editor.execute(
        """ALTER TABLE promotions_promotiontier
           ADD CONSTRAINT promotions_promotiontier_free_product_id_fk
           FOREIGN KEY (free_product_id) REFERENCES core_product(id) ON DELETE SET NULL;"""
    )

    # PackageItem.product
    schema_editor.execute("ALTER TABLE promotions_packageitem ADD COLUMN IF NOT EXISTS product_id_new uuid;")
    schema_editor.execute(
        """UPDATE promotions_packageitem pi
           SET product_id_new = cp.id
           FROM core_product cp
           WHERE pi.product_id::text = cp.legacy_id::text;"""
    )
    schema_editor.execute("ALTER TABLE promotions_packageitem DROP COLUMN product_id CASCADE;")
    schema_editor.execute("ALTER TABLE promotions_packageitem RENAME COLUMN product_id_new TO product_id;")
    schema_editor.execute(
        """ALTER TABLE promotions_packageitem
           ADD CONSTRAINT promotions_packageitem_product_id_fk
           FOREIGN KEY (product_id) REFERENCES core_product(id) ON DELETE SET NULL;"""
    )

    # M2M tables for Promotion.products, Promotion.combo_products, Promotion.exclude_products
    schema_editor.execute("ALTER TABLE promotions_promotion_products ADD COLUMN IF NOT EXISTS product_id_new uuid;")
    schema_editor.execute("ALTER TABLE promotions_promotion_combo_products ADD COLUMN IF NOT EXISTS product_id_new uuid;")
    schema_editor.execute("ALTER TABLE promotions_promotion_exclude_products ADD COLUMN IF NOT EXISTS product_id_new uuid;")

    schema_editor.execute(
        """UPDATE promotions_promotion_products pp
           SET product_id_new = cp.id
           FROM core_product cp
           WHERE pp.product_id::text = cp.legacy_id::text;"""
    )
    schema_editor.execute(
        """UPDATE promotions_promotion_combo_products pp
           SET product_id_new = cp.id
           FROM core_product cp
           WHERE pp.product_id::text = cp.legacy_id::text;"""
    )
    schema_editor.execute(
        """UPDATE promotions_promotion_exclude_products pp
           SET product_id_new = cp.id
           FROM core_product cp
           WHERE pp.product_id::text = cp.legacy_id::text;"""
    )

    schema_editor.execute("ALTER TABLE promotions_promotion_products DROP COLUMN product_id CASCADE;")
    schema_editor.execute("ALTER TABLE promotions_promotion_combo_products DROP COLUMN product_id CASCADE;")
    schema_editor.execute("ALTER TABLE promotions_promotion_exclude_products DROP COLUMN product_id CASCADE;")

    schema_editor.execute("ALTER TABLE promotions_promotion_products RENAME COLUMN product_id_new TO product_id;")
    schema_editor.execute("ALTER TABLE promotions_promotion_combo_products RENAME COLUMN product_id_new TO product_id;")
    schema_editor.execute("ALTER TABLE promotions_promotion_exclude_products RENAME COLUMN product_id_new TO product_id;")

    schema_editor.execute(
        """ALTER TABLE promotions_promotion_products
           ADD CONSTRAINT promotions_promotion_products_product_id_fk
           FOREIGN KEY (product_id) REFERENCES core_product(id) ON DELETE CASCADE;"""
    )
    schema_editor.execute(
        """ALTER TABLE promotions_promotion_combo_products
           ADD CONSTRAINT promotions_promotion_combo_products_product_id_fk
           FOREIGN KEY (product_id) REFERENCES core_product(id) ON DELETE CASCADE;"""
    )
    schema_editor.execute(
        """ALTER TABLE promotions_promotion_exclude_products
           ADD CONSTRAINT promotions_promotion_exclude_products_product_id_fk
           FOREIGN KEY (product_id) REFERENCES core_product(id) ON DELETE CASCADE;"""
    )


def reverse_migrate(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_convert_product_id_to_uuid'),
        ('promotions', '0002_add_deduction_strategy'),
    ]

    operations = [
        migrations.RunPython(migrate_promotion_product_ids, reverse_migrate),
    ]
