# Generated by Django 5.2.10 on 2026-01-31 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_product_modifier_model'),
        ('promotions', '0003_update_product_uuid_refs'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('full', 'Full Sync'), ('incremental', 'Incremental'), ('manual', 'Manual')], max_length=20)),
                ('sync_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], max_length=20)),
                ('promotions_received', models.IntegerField(default=0)),
                ('promotions_added', models.IntegerField(default=0)),
                ('promotions_updated', models.IntegerField(default=0)),
                ('promotions_deleted', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.TextField(blank=True)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('cms_version', models.CharField(blank=True, max_length=20)),
                ('edge_version', models.CharField(blank=True, max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.store')),
            ],
            options={
                'db_table': 'promotion_sync_log',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='promotionsynclog',
            index=models.Index(fields=['started_at'], name='promotion_s_started_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionsynclog',
            index=models.Index(fields=['sync_status'], name='promotion_s_sync_st_idx'),
        ),
    ]
