# Generated by Django 5.2.10 on 2026-01-31 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_add_promotion_sync_log'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DROP TABLE IF EXISTS promotions_promotion CASCADE;
                DROP TABLE IF EXISTS promotion_usage CASCADE;

                CREATE TABLE promotions_promotion (
                    id uuid NOT NULL PRIMARY KEY,
                    code varchar(50) NOT NULL UNIQUE,
                    name varchar(255) NOT NULL,
                    description text NOT NULL DEFAULT '',
                    terms_conditions text NOT NULL DEFAULT '',
                    company_id uuid NOT NULL,
                    brand_id uuid NOT NULL,
                    store_id uuid NULL,
                    promo_type varchar(50) NOT NULL,
                    apply_to varchar(20) NOT NULL,
                    execution_stage varchar(20) NOT NULL,
                    execution_priority integer NOT NULL DEFAULT 500,
                    is_active boolean NOT NULL DEFAULT true,
                    is_auto_apply boolean NOT NULL DEFAULT false,
                    require_voucher boolean NOT NULL DEFAULT false,
                    member_only boolean NOT NULL DEFAULT false,
                    is_stackable boolean NOT NULL DEFAULT false,
                    start_date date NOT NULL,
                    end_date date NOT NULL,
                    time_start time NULL,
                    time_end time NULL,
                    valid_days text NOT NULL DEFAULT '',
                    exclude_holidays boolean NOT NULL DEFAULT false,
                    rules_json text NOT NULL,
                    scope_json text NOT NULL DEFAULT '',
                    targeting_json text NOT NULL DEFAULT '',
                    max_uses integer NULL,
                    max_uses_per_customer integer NULL,
                    max_uses_per_day integer NULL,
                    current_uses integer NOT NULL DEFAULT 0,
                    compiled_at timestamptz NOT NULL,
                    synced_at timestamptz NOT NULL,
                    last_used_at timestamptz NULL,
                    CONSTRAINT promotions_promotion_company_id_fk FOREIGN KEY (company_id) REFERENCES core_company(id) DEFERRABLE INITIALLY DEFERRED,
                    CONSTRAINT promotions_promotion_brand_id_fk FOREIGN KEY (brand_id) REFERENCES core_brand(id) DEFERRABLE INITIALLY DEFERRED,
                    CONSTRAINT promotions_promotion_store_id_fk FOREIGN KEY (store_id) REFERENCES core_store(id) DEFERRABLE INITIALLY DEFERRED
                );

                CREATE INDEX promotions_promotion_company_store_idx ON promotions_promotion(company_id, store_id);
                CREATE INDEX promotions_promotion_brand_idx ON promotions_promotion(brand_id);
                CREATE INDEX promotions_promotion_active_dates_idx ON promotions_promotion(is_active, start_date, end_date);
                CREATE INDEX promotions_promotion_type_idx ON promotions_promotion(promo_type);
                CREATE INDEX promotions_promotion_code_idx ON promotions_promotion(code);

                CREATE TABLE promotion_usage (
                    id bigserial PRIMARY KEY,
                    promotion_id uuid NOT NULL,
                    promotion_code varchar(50) NOT NULL,
                    transaction_id uuid NOT NULL,
                    order_number varchar(50) NOT NULL DEFAULT '',
                    customer_id uuid NULL,
                    customer_phone varchar(20) NOT NULL DEFAULT '',
                    member_tier varchar(50) NOT NULL DEFAULT '',
                    discount_amount numeric(15, 2) NOT NULL,
                    original_amount numeric(15, 2) NOT NULL,
                    final_amount numeric(15, 2) NOT NULL,
                    brand_id uuid NOT NULL,
                    store_id uuid NOT NULL,
                    used_at timestamptz NOT NULL DEFAULT NOW(),
                    usage_date date NOT NULL,
                    CONSTRAINT promotion_usage_promotion_id_fk FOREIGN KEY (promotion_id) REFERENCES promotions_promotion(id) DEFERRABLE INITIALLY DEFERRED,
                    CONSTRAINT promotion_usage_brand_id_fk FOREIGN KEY (brand_id) REFERENCES core_brand(id) DEFERRABLE INITIALLY DEFERRED,
                    CONSTRAINT promotion_usage_store_id_fk FOREIGN KEY (store_id) REFERENCES core_store(id) DEFERRABLE INITIALLY DEFERRED
                );

                CREATE INDEX promotion_usage_promotion_date_idx ON promotion_usage(promotion_id, usage_date);
                CREATE INDEX promotion_usage_promotion_customer_date_idx ON promotion_usage(promotion_id, customer_id, usage_date);
                CREATE INDEX promotion_usage_transaction_idx ON promotion_usage(transaction_id);
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
