# Generated by Django 5.2.10 on 2026-01-31 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('station', models.CharField(max_length=20)),
                ('connection_type', models.CharField(choices=[('usb', 'USB'), ('network', 'Network'), ('bluetooth', 'Bluetooth')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.IntegerField(default=9100)),
                ('usb_vendor', models.CharField(blank=True, max_length=10)),
                ('usb_product', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='core.brand')),
            ],
        ),
        migrations.CreateModel(
            name='KitchenOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('served', 'Served')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('rush', 'Rush'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('target_prep_time', models.IntegerField(default=15, help_text='Target preparation time in minutes')),
                ('notified_10min', models.BooleanField(default=False)),
                ('notified_overdue', models.BooleanField(default=False)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_orders', to='pos.bill')),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
                'indexes': [models.Index(fields=['bill', 'station'], name='kitchen_kit_bill_id_e3652f_idx'), models.Index(fields=['status', 'created_at'], name='kitchen_kit_status_f3da57_idx'), models.Index(fields=['priority', 'created_at'], name='kitchen_kit_priorit_630cd8_idx')],
                'unique_together': {('bill', 'station')},
            },
        ),
        migrations.CreateModel(
            name='KitchenPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('total_orders', models.IntegerField(default=0)),
                ('completed_orders', models.IntegerField(default=0)),
                ('avg_prep_time', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('overdue_orders', models.IntegerField(default=0)),
                ('fastest_time', models.IntegerField(blank=True, null=True)),
                ('slowest_time', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_performance', to='core.brand')),
            ],
            options={
                'ordering': ['-date', 'station'],
                'unique_together': {('brand', 'station', 'date')},
            },
        ),
        migrations.CreateModel(
            name='KitchenStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
                ('target_prep_time', models.IntegerField(default=15, help_text='Default target prep time in minutes')),
                ('warning_threshold', models.IntegerField(default=10, help_text='Warning at X minutes')),
                ('color', models.CharField(default='blue', max_length=20)),
                ('icon', models.CharField(default='🍳', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_stations', to='core.brand')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'unique_together': {('brand', 'code')},
            },
        ),
    ]
