# Generated by Django 6.0.1 on 2026-01-17 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('station', models.CharField(max_length=20)),
                ('connection_type', models.CharField(choices=[('usb', 'USB'), ('network', 'Network'), ('bluetooth', 'Bluetooth')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.IntegerField(default=9100)),
                ('usb_vendor', models.CharField(blank=True, max_length=10)),
                ('usb_product', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='core.outlet')),
            ],
        ),
        migrations.CreateModel(
            name='KitchenOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('served', 'Served')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_orders', to='pos.bill')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['bill', 'station'], name='kitchen_kit_bill_id_e3652f_idx'), models.Index(fields=['status', 'created_at'], name='kitchen_kit_status_f3da57_idx')],
                'unique_together': {('bill', 'station')},
            },
        ),
    ]
