# Generated by Django 5.2.10 on 2026-02-06 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Brand code: HRPT, EPSON, XPRINTER', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Display name', max_length=100)),
                ('profile_class', models.CharField(help_text='Python class name: HRPTProfile, EpsonProfile', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Printer Brand',
                'verbose_name_plural': 'Printer Brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KitchenTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_target', models.CharField(db_index=True, help_text='Target station: kitchen, bar, dessert, etc.', max_length=50)),
                ('status', models.CharField(choices=[('new', 'New - Waiting to Print'), ('printing', 'Printing - In Progress'), ('printed', 'Printed - Success'), ('failed', 'Failed - Error')], db_index=True, default='new', max_length=20)),
                ('print_attempts', models.IntegerField(default=0, help_text='Number of print attempts')),
                ('max_retries', models.IntegerField(default=3, help_text='Max retry attempts')),
                ('printer_ip', models.CharField(blank=True, help_text='Printer that processed this ticket', max_length=255, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('is_reprint', models.BooleanField(default=False, help_text='Is this a reprint request?')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_tickets', to='pos.bill')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.brand')),
                ('original_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reprints', to='kitchen.kitchenticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='KitchenTicketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Quantity to print on this ticket')),
                ('bill_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_ticket_items', to='pos.billitem')),
                ('kitchen_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kitchen.kitchenticket')),
            ],
        ),
        migrations.CreateModel(
            name='KitchenTicketLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('created', 'Ticket Created'), ('print_start', 'Print Started'), ('print_success', 'Print Success'), ('print_failed', 'Print Failed'), ('retry', 'Retry Attempt'), ('manual_reset', 'Manual Reset'), ('marked_printed', 'Manually Marked as Printed'), ('marked_failed', 'Manually Marked as Failed')], db_index=True, max_length=50)),
                ('actor', models.CharField(help_text='Who/what triggered this: printer_service, admin:username, system', max_length=100)),
                ('printer_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Duration of action in milliseconds', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context: network latency, retry count, etc.')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='kitchen.kitchenticket')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PrinterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('station', models.CharField(max_length=20)),
                ('connection_type', models.CharField(choices=[('usb', 'USB'), ('network', 'Network'), ('bluetooth', 'Bluetooth')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.IntegerField(default=9100)),
                ('usb_vendor', models.CharField(blank=True, max_length=10)),
                ('usb_product', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='core.brand')),
            ],
        ),
        migrations.CreateModel(
            name='StationPrinter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(db_index=True, help_text='Station code: kitchen, bar, dessert, etc.', max_length=50)),
                ('printer_name', models.CharField(help_text='Friendly name for this printer', max_length=100)),
                ('printer_ip', models.CharField(help_text='IP address or hostname of ESC/POS printer', max_length=255)),
                ('printer_port', models.IntegerField(default=9100, help_text='Printer port (usually 9100)')),
                ('printer_brand', models.CharField(default='HRPT', help_text='Printer brand code: HRPT, EPSON, XPRINTER', max_length=20)),
                ('printer_type', models.CharField(choices=[('network', 'Network (RAW TCP/IP)'), ('win32', 'Windows Driver (Win32Raw)')], default='network', help_text='Connection type: network or win32', max_length=20)),
                ('timeout_seconds', models.IntegerField(default=5, help_text='Network timeout in seconds')),
                ('priority', models.IntegerField(default=1, help_text='Print priority (1=primary, 2=backup). Lower number = higher priority')),
                ('is_active', models.BooleanField(default=True)),
                ('paper_width_mm', models.IntegerField(default=80, help_text='Paper width in mm (58/80)')),
                ('chars_per_line', models.IntegerField(default=32, help_text='Characters per line')),
                ('last_print_at', models.DateTimeField(blank=True, help_text='Last successful print', null=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.TextField(blank=True)),
                ('total_prints', models.IntegerField(default=0)),
                ('failed_prints', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_printers', to='core.brand')),
            ],
            options={
                'ordering': ['station_code', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='PrinterHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_online', models.BooleanField(help_text='Printer responded to ping/connection test')),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('paper_status', models.CharField(choices=[('ok', 'OK'), ('low', 'Low'), ('out', 'Out'), ('jam', 'Paper Jam'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('temperature_ok', models.BooleanField(blank=True, help_text='Thermal printer temperature', null=True)),
                ('cutter_ok', models.BooleanField(blank=True, help_text='Auto-cutter status', null=True)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='kitchen.stationprinter')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='KitchenOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('served', 'Served')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('rush', 'Rush'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('target_prep_time', models.IntegerField(default=15, help_text='Target preparation time in minutes')),
                ('notified_10min', models.BooleanField(default=False)),
                ('notified_overdue', models.BooleanField(default=False)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_orders', to='pos.bill')),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
                'indexes': [models.Index(fields=['bill', 'station'], name='kitchen_kit_bill_id_e3652f_idx'), models.Index(fields=['status', 'created_at'], name='kitchen_kit_status_f3da57_idx'), models.Index(fields=['priority', 'created_at'], name='kitchen_kit_priorit_630cd8_idx')],
                'unique_together': {('bill', 'station')},
            },
        ),
        migrations.CreateModel(
            name='KitchenPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('total_orders', models.IntegerField(default=0)),
                ('completed_orders', models.IntegerField(default=0)),
                ('avg_prep_time', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('overdue_orders', models.IntegerField(default=0)),
                ('fastest_time', models.IntegerField(blank=True, null=True)),
                ('slowest_time', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_performance', to='core.brand')),
            ],
            options={
                'ordering': ['-date', 'station'],
                'unique_together': {('brand', 'station', 'date')},
            },
        ),
        migrations.CreateModel(
            name='KitchenStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
                ('target_prep_time', models.IntegerField(default=15, help_text='Default target prep time in minutes')),
                ('warning_threshold', models.IntegerField(default=10, help_text='Warning at X minutes')),
                ('color', models.CharField(default='blue', max_length=20)),
                ('icon', models.CharField(default='🍳', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_stations', to='core.brand')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'unique_together': {('brand', 'code')},
            },
        ),
        migrations.AddIndex(
            model_name='kitchenticket',
            index=models.Index(fields=['status', 'created_at'], name='kitchen_kit_status_b477b4_idx'),
        ),
        migrations.AddIndex(
            model_name='kitchenticket',
            index=models.Index(fields=['bill', 'printer_target'], name='kitchen_kit_bill_id_a5697a_idx'),
        ),
        migrations.AddIndex(
            model_name='kitchenticket',
            index=models.Index(fields=['brand', 'printer_target'], name='kitchen_kit_brand_i_b847ce_idx'),
        ),
        migrations.AddIndex(
            model_name='kitchenticket',
            index=models.Index(fields=['printer_target', 'status'], name='kitchen_kit_printer_75dae7_idx'),
        ),
        migrations.AddIndex(
            model_name='kitchenticket',
            index=models.Index(fields=['created_at'], name='kitchen_kit_created_055fec_idx'),
        ),
        migrations.AddIndex(
            model_name='kitchenticketitem',
            index=models.Index(fields=['kitchen_ticket', 'bill_item'], name='kitchen_kit_kitchen_3475a8_idx'),
        ),
        migrations.AddIndex(
            model_name='kitchenticketlog',
            index=models.Index(fields=['ticket', '-timestamp'], name='kitchen_kit_ticket__1bf7bf_idx'),
        ),
        migrations.AddIndex(
            model_name='kitchenticketlog',
            index=models.Index(fields=['action', '-timestamp'], name='kitchen_kit_action_6e3589_idx'),
        ),
        migrations.AddIndex(
            model_name='kitchenticketlog',
            index=models.Index(fields=['-timestamp'], name='kitchen_kit_timesta_cb5943_idx'),
        ),
        migrations.AddIndex(
            model_name='stationprinter',
            index=models.Index(fields=['station_code', 'is_active', 'priority'], name='kitchen_sta_station_767e74_idx'),
        ),
        migrations.AddIndex(
            model_name='stationprinter',
            index=models.Index(fields=['brand', 'station_code'], name='kitchen_sta_brand_i_1c032f_idx'),
        ),
        migrations.AddIndex(
            model_name='stationprinter',
            index=models.Index(fields=['printer_brand'], name='kitchen_sta_printer_ca9670_idx'),
        ),
        migrations.AddIndex(
            model_name='stationprinter',
            index=models.Index(fields=['printer_type'], name='kitchen_sta_printer_1e3e09_idx'),
        ),
        migrations.AddIndex(
            model_name='printerhealthcheck',
            index=models.Index(fields=['printer', '-checked_at'], name='kitchen_pri_printer_dd647c_idx'),
        ),
        migrations.AddIndex(
            model_name='printerhealthcheck',
            index=models.Index(fields=['-checked_at'], name='kitchen_pri_checked_d88a79_idx'),
        ),
        migrations.AddIndex(
            model_name='printerhealthcheck',
            index=models.Index(fields=['is_online', '-checked_at'], name='kitchen_pri_is_onli_804faa_idx'),
        ),
    ]
