# Generated by Django 5.2.11 on 2026-02-12 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_customer_review'),
        ('kitchen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckerTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(help_text='Template identifier', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('paper_width', models.IntegerField(default=80, help_text='Paper width in mm (58 or 80)')),
                ('header_line_1', models.CharField(blank=True, default='CHECKER', help_text='Main header text', max_length=100)),
                ('header_line_2', models.CharField(blank=True, default='Cek item sebelum disajikan', help_text='Sub header text', max_length=100)),
                ('show_bill_number', models.BooleanField(default=True)),
                ('show_table_number', models.BooleanField(default=True)),
                ('show_date_time', models.BooleanField(default=True)),
                ('show_station_label', models.BooleanField(default=True, help_text='Show station name (kitchen/bar/dessert) per item')),
                ('show_item_notes', models.BooleanField(default=True)),
                ('show_item_qty', models.BooleanField(default=True)),
                ('show_checkbox', models.BooleanField(default=True, help_text='Show [ ] checkbox per item')),
                ('footer_line_1', models.CharField(blank=True, default='CEK SEMUA ITEM SEBELUM DISAJIKAN', help_text='Footer message', max_length=100)),
                ('footer_line_2', models.CharField(blank=True, max_length=100)),
                ('auto_cut', models.BooleanField(default=True, help_text='Auto cut paper')),
                ('feed_lines', models.IntegerField(default=3, help_text='Lines to feed after print')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checker_templates', to='core.brand')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checker_templates', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checker_templates_created', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checker_templates', to='core.store')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checker_templates_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Checker Template',
                'verbose_name_plural': 'Checker Templates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='kitchen_che_company_81b54d_idx'), models.Index(fields=['brand', 'is_active'], name='kitchen_che_brand_i_895b7e_idx')],
            },
        ),
    ]
