# Generated by GitHub Copilot
from django.db import migrations, models


def backfill_ticket_brand(apps, schema_editor):
    # Use SQL to avoid joined field update restrictions
    schema_editor.execute(
        """
        UPDATE kitchen_kitchenticket kt
        SET brand_id = b.brand_id
        FROM pos_bill b
        WHERE kt.bill_id = b.id
          AND kt.brand_id IS NULL
          AND b.brand_id IS NOT NULL
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
        ('core', '0999_product_add_missing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenticket',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.PROTECT, to='core.brand'),
        ),
        migrations.RunPython(backfill_ticket_brand, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='kitchenticket',
            index=models.Index(fields=['brand', 'printer_target'], name='kitchen_kit_brand_printer_idx'),
        ),
    ]