# Generated by Django 5.2.10 on 2026-02-04 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recreate_productphoto'),
        ('kitchen', '0001_initial'),
        ('pos', '0002_add_printer_target_to_billitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_target', models.CharField(db_index=True, help_text='Target station: kitchen, bar, dessert, etc.', max_length=50)),
                ('status', models.CharField(choices=[('new', 'New - Waiting to Print'), ('printing', 'Printing - In Progress'), ('printed', 'Printed - Success'), ('failed', 'Failed - Error')], db_index=True, default='new', max_length=20)),
                ('print_attempts', models.IntegerField(default=0, help_text='Number of print attempts')),
                ('max_retries', models.IntegerField(default=3, help_text='Max retry attempts')),
                ('printer_ip', models.GenericIPAddressField(blank=True, help_text='Printer that processed this ticket', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('is_reprint', models.BooleanField(default=False, help_text='Is this a reprint request?')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_tickets', to='pos.bill')),
                ('original_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reprints', to='kitchen.kitchenticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='KitchenTicketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Quantity to print on this ticket')),
                ('bill_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_ticket_items', to='pos.billitem')),
                ('kitchen_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kitchen.kitchenticket')),
            ],
        ),
        migrations.CreateModel(
            name='StationPrinter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(db_index=True, help_text='Station code: kitchen, bar, dessert, etc.', max_length=50)),
                ('printer_name', models.CharField(help_text='Friendly name for this printer', max_length=100)),
                ('printer_ip', models.GenericIPAddressField(help_text='IP address of ESC/POS printer')),
                ('printer_port', models.IntegerField(default=9100, help_text='Printer port (usually 9100)')),
                ('priority', models.IntegerField(default=1, help_text='Print priority (1=primary, 2=backup). Lower number = higher priority')),
                ('is_active', models.BooleanField(default=True)),
                ('paper_width_mm', models.IntegerField(default=80, help_text='Paper width in mm (58/80)')),
                ('chars_per_line', models.IntegerField(default=32, help_text='Characters per line')),
                ('last_print_at', models.DateTimeField(blank=True, help_text='Last successful print', null=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.TextField(blank=True)),
                ('total_prints', models.IntegerField(default=0)),
                ('failed_prints', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_printers', to='core.brand')),
            ],
            options={
                'ordering': ['station_code', 'priority'],
            },
        ),
        migrations.AddIndex(
            model_name='kitchenticket',
            index=models.Index(fields=['status', 'created_at'], name='kitchen_kit_status_b477b4_idx'),
        ),
        migrations.AddIndex(
            model_name='kitchenticket',
            index=models.Index(fields=['bill', 'printer_target'], name='kitchen_kit_bill_id_a5697a_idx'),
        ),
        migrations.AddIndex(
            model_name='kitchenticket',
            index=models.Index(fields=['printer_target', 'status'], name='kitchen_kit_printer_75dae7_idx'),
        ),
        migrations.AddIndex(
            model_name='kitchenticket',
            index=models.Index(fields=['created_at'], name='kitchen_kit_created_055fec_idx'),
        ),
        migrations.AddIndex(
            model_name='kitchenticketitem',
            index=models.Index(fields=['kitchen_ticket', 'bill_item'], name='kitchen_kit_kitchen_3475a8_idx'),
        ),
        migrations.AddIndex(
            model_name='stationprinter',
            index=models.Index(fields=['station_code', 'is_active', 'priority'], name='kitchen_sta_station_767e74_idx'),
        ),
        migrations.AddIndex(
            model_name='stationprinter',
            index=models.Index(fields=['brand', 'station_code'], name='kitchen_sta_brand_i_1c032f_idx'),
        ),
    ]
