# Generated by Django 6.0.1 on 2026-01-17 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_storesession_eodchecklist_cashiershift_and_more'),
        ('kitchen', '0001_initial'),
        ('pos', '0003_alter_payment_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('total_orders', models.IntegerField(default=0)),
                ('completed_orders', models.IntegerField(default=0)),
                ('avg_prep_time', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('overdue_orders', models.IntegerField(default=0)),
                ('fastest_time', models.IntegerField(blank=True, null=True)),
                ('slowest_time', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'station'],
            },
        ),
        migrations.CreateModel(
            name='KitchenStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
                ('target_prep_time', models.IntegerField(default=15, help_text='Default target prep time in minutes')),
                ('warning_threshold', models.IntegerField(default=10, help_text='Warning at X minutes')),
                ('color', models.CharField(default='blue', max_length=20)),
                ('icon', models.CharField(default='🍳', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='kitchenorder',
            options={'ordering': ['-priority', 'created_at']},
        ),
        migrations.AddField(
            model_name='kitchenorder',
            name='notified_10min',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kitchenorder',
            name='notified_overdue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kitchenorder',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('rush', 'Rush'), ('urgent', 'Urgent')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='kitchenorder',
            name='target_prep_time',
            field=models.IntegerField(default=15, help_text='Target preparation time in minutes'),
        ),
        migrations.AddIndex(
            model_name='kitchenorder',
            index=models.Index(fields=['priority', 'created_at'], name='kitchen_kit_priorit_630cd8_idx'),
        ),
        migrations.AddField(
            model_name='kitchenperformance',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_performance', to='core.outlet'),
        ),
        migrations.AddField(
            model_name='kitchenstation',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_stations', to='core.outlet'),
        ),
        migrations.AlterUniqueTogether(
            name='kitchenperformance',
            unique_together={('outlet', 'station', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='kitchenstation',
            unique_together={('outlet', 'code')},
        ),
    ]
