# Generated by Django 5.2.10 on 2026-02-04 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_add_kitchen_printer_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenTicketLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('created', 'Ticket Created'), ('print_start', 'Print Started'), ('print_success', 'Print Success'), ('print_failed', 'Print Failed'), ('retry', 'Retry Attempt'), ('manual_reset', 'Manual Reset'), ('marked_printed', 'Manually Marked as Printed'), ('marked_failed', 'Manually Marked as Failed')], db_index=True, max_length=50)),
                ('actor', models.CharField(help_text='Who/what triggered this: printer_service, admin:username, system', max_length=100)),
                ('printer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Duration of action in milliseconds', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context: network latency, retry count, etc.')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='kitchen.kitchenticket')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ticket', '-timestamp'], name='kitchen_kit_ticket__1bf7bf_idx'), models.Index(fields=['action', '-timestamp'], name='kitchen_kit_action_6e3589_idx'), models.Index(fields=['-timestamp'], name='kitchen_kit_timesta_cb5943_idx')],
            },
        ),
        migrations.CreateModel(
            name='PrinterHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_online', models.BooleanField(help_text='Printer responded to ping/connection test')),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('paper_status', models.CharField(choices=[('ok', 'OK'), ('low', 'Low'), ('out', 'Out'), ('jam', 'Paper Jam'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('temperature_ok', models.BooleanField(blank=True, help_text='Thermal printer temperature', null=True)),
                ('cutter_ok', models.BooleanField(blank=True, help_text='Auto-cutter status', null=True)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='kitchen.stationprinter')),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['printer', '-checked_at'], name='kitchen_pri_printer_dd647c_idx'), models.Index(fields=['-checked_at'], name='kitchen_pri_checked_d88a79_idx'), models.Index(fields=['is_online', '-checked_at'], name='kitchen_pri_is_onli_804faa_idx')],
            },
        ),
    ]
