# Generated by Django 5.2.11 on 2026-02-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_kitchentickettemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchenperformance',
            name='avg_prep_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
