# Generated by Django 5.2.11 on 2026-02-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0004_increase_avg_prep_time_precision'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kitchenorder',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='kitchenorder',
            name='item_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
