# Generated by Django 5.2.10 on 2026-02-04 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membertransaction',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_transactions', to='pos.bill'),
        ),
        migrations.AddField(
            model_name='membertransaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membertransaction',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.member'),
        ),
        migrations.AddField(
            model_name='modifier',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='core.brand'),
        ),
        migrations.AddField(
            model_name='modifieroption',
            name='modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.modifier'),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Brand this terminal serves (required for multi-brand stores)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terminals', to='core.brand'),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashiershift',
            name='terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='core.posterminal'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.category'),
        ),
        migrations.AddField(
            model_name='productmodifier',
            name='modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_modifiers', to='core.modifier'),
        ),
        migrations.AddField(
            model_name='productmodifier',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_modifiers', to='core.product'),
        ),
        migrations.AddField(
            model_name='productphoto',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.product'),
        ),
        migrations.AddField(
            model_name='shiftpaymentsummary',
            name='cashier_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_summaries', to='core.cashiershift'),
        ),
        migrations.AddField(
            model_name='store',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='core.company'),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to='core.store'),
        ),
        migrations.AddField(
            model_name='cashdrop',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_drops', to='core.store'),
        ),
        migrations.AddField(
            model_name='businessdatealert',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.store'),
        ),
        migrations.AddField(
            model_name='storebrand',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_stores', to='core.brand'),
        ),
        migrations.AddField(
            model_name='storebrand',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_brands', to='core.store'),
        ),
        migrations.AddField(
            model_name='storesession',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_closed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storesession',
            name='opened_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_opened', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storesession',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='core.store'),
        ),
        migrations.AddField(
            model_name='eodchecklist',
            name='store_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='core.storesession'),
        ),
        migrations.AddField(
            model_name='cashiershift',
            name='store_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='core.storesession'),
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('company', 'code')},
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['company', 'member_code'], name='core_member_company_feb7c4_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['company', 'phone'], name='core_member_company_96ea13_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['company', 'is_active'], name='core_member_company_c8b9df_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['tier', 'is_active'], name='core_member_tier_86d753_idx'),
        ),
        migrations.AddIndex(
            model_name='membertransaction',
            index=models.Index(fields=['member', 'created_at'], name='core_member_member__e0be6a_idx'),
        ),
        migrations.AddIndex(
            model_name='membertransaction',
            index=models.Index(fields=['transaction_type', 'created_at'], name='core_member_transac_a036f3_idx'),
        ),
        migrations.AddIndex(
            model_name='modifier',
            index=models.Index(fields=['brand', 'is_active'], name='core_modifi_brand_i_b53308_idx'),
        ),
        migrations.AddIndex(
            model_name='modifieroption',
            index=models.Index(fields=['modifier', 'is_active'], name='core_modifi_modifie_9b4abe_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'is_active'], name='core_produc_brand_i_a8b2f3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'category'], name='core_produc_brand_i_a6104e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('brand', 'category', 'name', 'sku')},
        ),
        migrations.AddIndex(
            model_name='productmodifier',
            index=models.Index(fields=['product'], name='core_produc_product_941584_idx'),
        ),
        migrations.AddIndex(
            model_name='productmodifier',
            index=models.Index(fields=['modifier'], name='core_produc_modifie_08093b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productmodifier',
            unique_together={('product', 'modifier')},
        ),
        migrations.AddIndex(
            model_name='productphoto',
            index=models.Index(fields=['product', 'is_primary'], name='core_produc_product_a76660_idx'),
        ),
        migrations.AddIndex(
            model_name='productphoto',
            index=models.Index(fields=['product', 'sort_order'], name='core_produc_product_a117ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shiftpaymentsummary',
            unique_together={('cashier_shift', 'payment_method')},
        ),
        migrations.AddIndex(
            model_name='posterminal',
            index=models.Index(fields=['terminal_code'], name='core_poster_termina_c4bae4_idx'),
        ),
        migrations.AddIndex(
            model_name='posterminal',
            index=models.Index(fields=['is_active', 'last_heartbeat'], name='core_poster_is_acti_5db1bc_idx'),
        ),
        migrations.AddIndex(
            model_name='cashdrop',
            index=models.Index(fields=['company', 'brand', 'store'], name='core_cash_d_company_6cc002_idx'),
        ),
        migrations.AddIndex(
            model_name='cashdrop',
            index=models.Index(fields=['cashier_shift', 'created_at'], name='core_cash_d_cashier_624c20_idx'),
        ),
        migrations.AddIndex(
            model_name='cashdrop',
            index=models.Index(fields=['created_by', 'created_at'], name='core_cash_d_created_3126d6_idx'),
        ),
        migrations.AddIndex(
            model_name='cashdrop',
            index=models.Index(fields=['receipt_number'], name='core_cash_d_receipt_0e4808_idx'),
        ),
        migrations.AddIndex(
            model_name='businessdatealert',
            index=models.Index(fields=['store', 'acknowledged', 'severity'], name='core_busine_store_i_f719e4_idx'),
        ),
        migrations.AddIndex(
            model_name='businessdatealert',
            index=models.Index(fields=['alert_type', 'created_at'], name='core_busine_alert_t_65aaec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storebrand',
            unique_together={('store', 'brand')},
        ),
        migrations.AddIndex(
            model_name='storesession',
            index=models.Index(fields=['store', 'is_current'], name='core_stores_store_i_fc84b5_idx'),
        ),
        migrations.AddIndex(
            model_name='storesession',
            index=models.Index(fields=['store', 'business_date'], name='core_stores_store_i_07590f_idx'),
        ),
        migrations.AddIndex(
            model_name='storesession',
            index=models.Index(fields=['status', 'opened_at'], name='core_stores_status_afa9a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storesession',
            unique_together={('store', 'business_date', 'session_number')},
        ),
        migrations.AddIndex(
            model_name='cashiershift',
            index=models.Index(fields=['store_session', 'cashier'], name='core_cashie_store_s_1b8e31_idx'),
        ),
        migrations.AddIndex(
            model_name='cashiershift',
            index=models.Index(fields=['cashier', 'shift_start'], name='core_cashie_cashier_da0554_idx'),
        ),
        migrations.AddIndex(
            model_name='cashiershift',
            index=models.Index(fields=['terminal', 'status'], name='core_cashie_termina_4cb27e_idx'),
        ),
    ]
