# Generated by Django 6.0.1 on 2026-01-17 03:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_date', models.DateField()),
                ('session_number', models.IntegerField(default=1)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('force_closed', 'Force Closed')], default='open', max_length=20)),
                ('is_current', models.BooleanField(default=False)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('eod_notes', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_closed', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_opened', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='core.storeconfig')),
            ],
            options={
                'ordering': ['-business_date', '-session_number'],
            },
        ),
        migrations.CreateModel(
            name='EODChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checklist_item', models.CharField(max_length=200)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('store_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='core.storesession')),
            ],
            options={
                'ordering': ['checklist_item'],
            },
        ),
        migrations.CreateModel(
            name='CashierShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shift_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('shift_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('abandoned', 'Abandoned')], default='open', max_length=20)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cash_difference', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashier_shifts', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts_closed', to=settings.AUTH_USER_MODEL)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='core.posterminal')),
                ('store_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='core.storesession')),
            ],
            options={
                'ordering': ['-shift_start'],
            },
        ),
        migrations.CreateModel(
            name='BusinessDateAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('eod_overdue', 'EOD Overdue'), ('shift_overtime', 'Shift Overtime'), ('cash_variance', 'Cash Variance'), ('session_anomaly', 'Session Anomaly')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.storeconfig')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', 'acknowledged', 'severity'], name='core_busine_store_i_f719e4_idx'), models.Index(fields=['alert_type', 'created_at'], name='core_busine_alert_t_65aaec_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShiftPaymentSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('qris', 'QRIS'), ('transfer', 'Bank Transfer'), ('ewallet', 'E-Wallet'), ('voucher', 'Voucher')], max_length=20)),
                ('expected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transaction_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('cashier_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_summaries', to='core.cashiershift')),
            ],
            options={
                'ordering': ['payment_method'],
                'unique_together': {('cashier_shift', 'payment_method')},
            },
        ),
        migrations.AddIndex(
            model_name='storesession',
            index=models.Index(fields=['store', 'is_current'], name='core_stores_store_i_fc84b5_idx'),
        ),
        migrations.AddIndex(
            model_name='storesession',
            index=models.Index(fields=['store', 'business_date'], name='core_stores_store_i_07590f_idx'),
        ),
        migrations.AddIndex(
            model_name='storesession',
            index=models.Index(fields=['status', 'opened_at'], name='core_stores_status_afa9a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storesession',
            unique_together={('store', 'business_date', 'session_number')},
        ),
        migrations.AddIndex(
            model_name='cashiershift',
            index=models.Index(fields=['store_session', 'cashier'], name='core_cashie_store_s_1b8e31_idx'),
        ),
        migrations.AddIndex(
            model_name='cashiershift',
            index=models.Index(fields=['cashier', 'shift_start'], name='core_cashie_cashier_da0554_idx'),
        ),
        migrations.AddIndex(
            model_name='cashiershift',
            index=models.Index(fields=['terminal', 'status'], name='core_cashie_termina_4cb27e_idx'),
        ),
    ]
