# Generated by Django 5.2.10 on 2026-02-07 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDisplaySlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Slide title (for admin only)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description (for admin only)')),
                ('image_url', models.URLField(help_text='Full MinIO URL to image', max_length=500)),
                ('image_path', models.CharField(help_text='MinIO object path (bucket/key)', max_length=500)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower = first)')),
                ('duration_seconds', models.IntegerField(default=5, help_text='How long to show this slide')),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, help_text='Start showing from this date (optional)', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Stop showing after this date (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_slides', to='core.brand')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_slides', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slides_created', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_slides', to='core.store')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slides_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Display Slide',
                'verbose_name_plural': 'Customer Display Slides',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['company', 'is_active', 'order'], name='core_custom_company_540ddc_idx'), models.Index(fields=['brand', 'is_active', 'order'], name='core_custom_brand_i_40f56a_idx'), models.Index(fields=['store', 'is_active', 'order'], name='core_custom_store_i_837668_idx')],
            },
        ),
    ]
