# Generated by Django 6.0.1 on 2026-01-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_productphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfig',
            name='login_image',
            field=models.ImageField(blank=True, help_text='Image for login page (recommended 1080x1920)', null=True, upload_to='login_images/'),
        ),
    ]
