# Generated by Django 5.2.10 on 2026-02-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customerdisplayslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='posterminal',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='Last activity timestamp', null=True),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='session_token',
            field=models.UUIDField(blank=True, help_text='Launcher session token', null=True),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, help_text='Session token expiry', null=True),
        ),
    ]
