# Generated by Django 5.2.10 on 2026-02-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_posterminal_session_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='posterminal',
            name='print_to',
            field=models.CharField(
                choices=[('printer', 'Printer'), ('file', 'File')],
                default='printer',
                help_text='Print destination: printer or file (for development)',
                max_length=20
            ),
        ),
    ]
