# Generated by Django 5.2.10 on 2026-02-09 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_print_checker_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='posterminal',
            name='auto_print_kitchen_order',
            field=models.BooleanField(default=True, help_text='Auto print kitchen tickets'),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='auto_print_receipt',
            field=models.BooleanField(default=False, help_text='Auto print after payment'),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='barcode_scanner_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='cash_drawer_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='customer_pole_display_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='default_payment_methods',
            field=models.JSONField(blank=True, default=list, help_text='Default payment methods enabled for this terminal (e.g., ["cash", "qris", "card"])'),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='edc_integration_mode',
            field=models.CharField(choices=[('none', 'No EDC Integration'), ('manual', 'Manual Entry'), ('api', 'API Integration')], default='none', help_text='EDC/Card payment integration mode', max_length=20),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='enable_customer_display',
            field=models.BooleanField(default=False, help_text='Enable dual display for customer'),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='enable_kitchen_display',
            field=models.BooleanField(default=False, help_text='Enable kitchen display screen'),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='enable_kitchen_printer',
            field=models.BooleanField(default=True, help_text='Enable kitchen printer'),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='kitchen_printer_name',
            field=models.CharField(blank=True, help_text='Kitchen printer name/path', max_length=200),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='print_logo_on_receipt',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='printer_type',
            field=models.CharField(choices=[('thermal', 'Thermal Printer (58mm/80mm)'), ('dot_matrix', 'Dot Matrix'), ('laser', 'Laser Printer'), ('none', 'No Printer')], default='thermal', max_length=20),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='receipt_paper_width',
            field=models.IntegerField(default=80, help_text='Paper width in mm (58 or 80)'),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='receipt_printer_name',
            field=models.CharField(blank=True, help_text='Receipt printer name/path', max_length=200),
        ),
        migrations.CreateModel(
            name='CustomerDisplayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(help_text='Display name on customer screen', max_length=200)),
                ('brand_logo_url', models.URLField(help_text='Logo URL (MinIO)', max_length=500)),
                ('brand_tagline', models.CharField(blank=True, help_text='Tagline below brand name', max_length=200)),
                ('running_text', models.TextField(help_text='Scrolling text at bottom of screen')),
                ('running_text_speed', models.IntegerField(default=50, help_text='Scroll speed (pixels per second)')),
                ('theme_primary_color', models.CharField(default='#4F46E5', help_text='Primary color (hex)', max_length=20)),
                ('theme_secondary_color', models.CharField(default='#10B981', help_text='Secondary color (hex)', max_length=20)),
                ('theme_text_color', models.CharField(default='#1F2937', help_text='Main text color (hex)', max_length=20)),
                ('theme_billing_bg', models.CharField(default='gradient', help_text='Billing section background', max_length=50)),
                ('theme_billing_text', models.CharField(default='#FFFFFF', help_text='Billing text color (hex)', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='display_configs', to='core.brand')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_configs', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='display_configs_created', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='display_configs', to='core.store')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='display_configs_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Display Config',
                'verbose_name_plural': 'Customer Display Configs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='core_custom_company_10a5fe_idx'), models.Index(fields=['brand', 'is_active'], name='core_custom_brand_i_9759fe_idx'), models.Index(fields=['store', 'is_active'], name='core_custom_store_i_a8545b_idx')],
                'unique_together': {('company', 'brand', 'store')},
            },
        ),
        migrations.CreateModel(
            name='ReceiptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(help_text='Template identifier', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('paper_width', models.IntegerField(default=58, help_text='Paper width in mm (58 or 80)')),
                ('show_logo', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, help_text='Receipt logo image', null=True, upload_to='receipt_logos/')),
                ('header_line_1', models.CharField(blank=True, help_text='Store name / company', max_length=100)),
                ('header_line_2', models.CharField(blank=True, help_text='Address line 1', max_length=100)),
                ('header_line_3', models.CharField(blank=True, help_text='Address line 2 / Phone', max_length=100)),
                ('header_line_4', models.CharField(blank=True, help_text='Tax ID / Additional info', max_length=100)),
                ('show_receipt_number', models.BooleanField(default=True)),
                ('show_date_time', models.BooleanField(default=True)),
                ('show_cashier_name', models.BooleanField(default=True)),
                ('show_customer_name', models.BooleanField(default=True)),
                ('show_table_number', models.BooleanField(default=True)),
                ('show_item_code', models.BooleanField(default=False)),
                ('show_item_category', models.BooleanField(default=False)),
                ('show_modifiers', models.BooleanField(default=True)),
                ('price_alignment', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='right', max_length=10)),
                ('show_currency_symbol', models.BooleanField(default=True)),
                ('show_subtotal', models.BooleanField(default=True)),
                ('show_tax', models.BooleanField(default=True)),
                ('show_service_charge', models.BooleanField(default=True)),
                ('show_discount', models.BooleanField(default=True)),
                ('show_payment_method', models.BooleanField(default=True)),
                ('show_paid_amount', models.BooleanField(default=True)),
                ('show_change', models.BooleanField(default=True)),
                ('footer_line_1', models.CharField(blank=True, help_text='Thank you message', max_length=100)),
                ('footer_line_2', models.CharField(blank=True, help_text='Additional info', max_length=100)),
                ('footer_line_3', models.CharField(blank=True, help_text='Website / Social media', max_length=100)),
                ('show_qr_payment', models.BooleanField(default=False, help_text='Show payment QR code')),
                ('auto_print', models.BooleanField(default=True, help_text='Auto print after order')),
                ('auto_cut', models.BooleanField(default=True, help_text='Auto cut paper')),
                ('feed_lines', models.IntegerField(default=3, help_text='Lines to feed after print')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_templates', to='core.brand')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_templates', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_templates_created', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_templates', to='core.store')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_templates_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receipt Template',
                'verbose_name_plural': 'Receipt Templates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='core_receip_company_36e9cd_idx'), models.Index(fields=['brand', 'is_active'], name='core_receip_brand_i_7f118e_idx'), models.Index(fields=['store', 'is_active'], name='core_receip_store_i_d2034e_idx')],
            },
        ),
    ]
