# Generated by Django 5.2.10 on 2026-02-09 15:24

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_receipttemplate_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('cafe', 'Cafe'), ('fast_food', 'Fast Food'), ('food_court', 'Food Court'), ('bakery', 'Bakery'), ('bar', 'Bar'), ('other', 'Other')], default='restaurant', help_text='Type of brand/concept', max_length=50),
        ),
        migrations.AlterField(
            model_name='receipttemplate',
            name='logo',
            field=models.ImageField(blank=True, help_text='Receipt logo image', null=True, upload_to=apps.core.models.receipt_logo_upload_path),
        ),
    ]
