# Generated by Django 5.2.10 on 2026-02-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_brand_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_type',
            field=models.CharField(default='restaurant', help_text='Type of brand/concept (synced from HO)', max_length=50),
        ),
    ]
