# Generated by Django 5.2.10 on 2026-02-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_brand_type_remove_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdisplayconfig',
            name='brand_logo',
            field=models.ImageField(blank=True, help_text='Upload brand logo', null=True, upload_to='display_logos/'),
        ),
        migrations.AlterField(
            model_name='customerdisplayconfig',
            name='brand_logo_url',
            field=models.URLField(blank=True, help_text='Logo URL (MinIO) - optional if logo uploaded', max_length=500),
        ),
    ]
