# Generated by Django 5.2.11 on 2026-02-11 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_customerdisplayconfig_brand_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashiershift',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashier_shifts', to='core.brand'),
        ),
        migrations.AddField(
            model_name='cashiershift',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashier_shifts', to='core.company'),
        ),
        migrations.AddField(
            model_name='cashiershift',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashier_shifts', to='core.store'),
        ),
        migrations.AddIndex(
            model_name='cashiershift',
            index=models.Index(fields=['company', 'brand', 'store'], name='core_cashie_company_459600_idx'),
        ),
    ]
