# Generated by Django 5.2.11 on 2026-02-12 03:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_multi_tenant_to_cashier_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('orafin_group', models.CharField(blank=True, help_text='Orafin mapping group for financial integration', max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_groups', to='core.company')),
            ],
            options={
                'db_table': 'core_media_group',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='PaymentMethodProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_id', models.IntegerField(default=0, help_text='Media ID from backoffice keyboard mapping')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('color', models.CharField(default='#6b7280', help_text='Button color hex', max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Icon identifier', max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('smallest_denomination', models.IntegerField(default=0, help_text='Smallest denomination allowed (0 = any amount)')),
                ('allow_change', models.BooleanField(default=False, help_text='Whether overpayment returns change (True for cash)')),
                ('open_cash_drawer', models.BooleanField(default=False, help_text='Whether to trigger cash drawer on this payment method')),
                ('legacy_method_id', models.CharField(blank=True, help_text='Maps to old method IDs: cash, card, qris, ewallet, transfer, voucher, debit', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_profiles', to='core.brand')),
                ('media_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_profiles', to='core.mediagroup')),
            ],
            options={
                'db_table': 'core_payment_method_profile',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DataEntryPrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('amount', 'Amount'), ('text', 'Text Input'), ('numeric', 'Numeric Input'), ('scanner', 'Scanner Input')], default='text', max_length=20)),
                ('min_length', models.IntegerField(default=0, help_text='Minimum input length (0 = optional)')),
                ('max_length', models.IntegerField(default=99, help_text='Maximum input length')),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('use_scanner', models.BooleanField(default=False, help_text='Enable barcode/QR scanner for this field')),
                ('is_required', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='core.paymentmethodprofile')),
            ],
            options={
                'db_table': 'core_data_entry_prompt',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='posterminal',
            name='payment_profiles',
            field=models.ManyToManyField(blank=True, help_text='Payment method profiles assigned to this terminal', related_name='terminals', to='core.paymentmethodprofile'),
        ),
        migrations.AddIndex(
            model_name='paymentmethodprofile',
            index=models.Index(fields=['brand', 'is_active'], name='core_paymen_brand_i_879553_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentmethodprofile',
            unique_together={('brand', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='dataentryprompt',
            unique_together={('profile', 'field_name')},
        ),
    ]
