# Generated by Django 5.2.11 on 2026-02-12 13:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_eft_terminal'),
        ('pos', '0006_payment_eft_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_reviews', to='pos.bill')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_reviews', to='core.store')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_reviews', to='core.posterminal')),
            ],
            options={
                'db_table': 'core_customer_review',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', 'created_at'], name='core_custom_store_i_a3611f_idx'), models.Index(fields=['rating', 'created_at'], name='core_custom_rating_b1295c_idx')],
            },
        ),
    ]
