# Generated by Django 5.2.11 on 2026-02-13 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_payment_profile_company_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDisplayPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Promo title shown on card', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Short description (max 2 lines)', max_length=500)),
                ('badge_text', models.CharField(help_text='Badge label e.g. HOT DEAL, LIMITED, WEEKEND', max_length=30)),
                ('badge_color', models.CharField(choices=[('red', 'Red'), ('orange', 'Orange'), ('purple', 'Purple'), ('green', 'Green'), ('blue', 'Blue')], default='red', max_length=20)),
                ('image_url', models.URLField(blank=True, help_text='Full MinIO URL to promo image', max_length=500)),
                ('image_path', models.CharField(blank=True, help_text='MinIO object path (bucket/key)', max_length=500)),
                ('emoji_fallback', models.CharField(default='🍽️', help_text='Fallback emoji if image fails to load', max_length=10)),
                ('original_price', models.DecimalField(decimal_places=0, default=0, help_text='Original price (strikethrough)', max_digits=12)),
                ('promo_price', models.DecimalField(decimal_places=0, default=0, help_text='Discounted price', max_digits=12)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, help_text='Start showing from this date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Stop showing after this date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer Display Promo',
                'verbose_name_plural': 'Customer Display Promos',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='paymentmethodprofile',
            new_name='core_paymen_company_c96993_idx',
            old_name='core_paymen_company_6b1c2e_idx',
        ),
        migrations.AddField(
            model_name='customerdisplaypromo',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_promos', to='core.brand'),
        ),
        migrations.AddField(
            model_name='customerdisplaypromo',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_promos', to='core.company'),
        ),
        migrations.AddField(
            model_name='customerdisplaypromo',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_promos', to='core.store'),
        ),
        migrations.AddIndex(
            model_name='customerdisplaypromo',
            index=models.Index(fields=['company', 'is_active', 'order'], name='core_custom_company_996659_idx'),
        ),
        migrations.AddIndex(
            model_name='customerdisplaypromo',
            index=models.Index(fields=['brand', 'is_active', 'order'], name='core_custom_brand_i_f5f804_idx'),
        ),
        migrations.AddIndex(
            model_name='customerdisplaypromo',
            index=models.Index(fields=['store', 'is_active', 'order'], name='core_custom_store_i_6c8dbd_idx'),
        ),
    ]
