# Generated by Django 5.2.11 on 2026-02-13 21:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('terms_conditions', models.TextField(blank=True, default='')),
                ('promo_type', models.CharField(max_length=50)),
                ('apply_to', models.CharField(max_length=20)),
                ('execution_stage', models.CharField(max_length=20)),
                ('execution_priority', models.IntegerField(default=500)),
                ('is_active', models.BooleanField(default=True)),
                ('is_auto_apply', models.BooleanField(default=False)),
                ('require_voucher', models.BooleanField(default=False)),
                ('member_only', models.BooleanField(default=False)),
                ('is_stackable', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('time_start', models.TimeField(blank=True, null=True)),
                ('time_end', models.TimeField(blank=True, null=True)),
                ('valid_days', models.TextField(blank=True, default='')),
                ('exclude_holidays', models.BooleanField(default=False)),
                ('rules_json', models.TextField()),
                ('scope_json', models.TextField(blank=True, default='')),
                ('targeting_json', models.TextField(blank=True, default='')),
                ('max_uses', models.IntegerField(blank=True, null=True)),
                ('max_uses_per_customer', models.IntegerField(blank=True, null=True)),
                ('max_uses_per_day', models.IntegerField(blank=True, null=True)),
                ('current_uses', models.IntegerField(default=0)),
                ('compiled_at', models.DateTimeField()),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='core.brand')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='core.company')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='core.store')),
            ],
            options={
                'db_table': 'promotions_promotion',
                'ordering': ['-start_date', 'execution_priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PromotionSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('full', 'Full Sync'), ('incremental', 'Incremental'), ('manual', 'Manual')], max_length=20)),
                ('sync_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], max_length=20)),
                ('promotions_received', models.IntegerField(default=0)),
                ('promotions_added', models.IntegerField(default=0)),
                ('promotions_updated', models.IntegerField(default=0)),
                ('promotions_deleted', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.TextField(blank=True)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('cms_version', models.CharField(blank=True, max_length=20)),
                ('edge_version', models.CharField(blank=True, max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.store')),
            ],
            options={
                'db_table': 'promotion_sync_log',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_code', models.CharField(max_length=50)),
                ('transaction_id', models.UUIDField()),
                ('order_number', models.CharField(blank=True, max_length=50)),
                ('customer_id', models.UUIDField(blank=True, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('member_tier', models.CharField(blank=True, max_length=50)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('usage_date', models.DateField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.brand')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='promotions.promotion')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.store')),
            ],
            options={
                'db_table': 'promotion_usage',
            },
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['company', 'store'], name='promotions__company_866f74_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['brand'], name='promotions__brand_i_d69c81_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['is_active', 'start_date', 'end_date'], name='promotions__is_acti_6fdf95_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['promo_type'], name='promotions__promo_t_d87c07_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['code'], name='promotions__code_e9f529_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionsynclog',
            index=models.Index(fields=['started_at'], name='promotion_s_started_05ec7b_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionsynclog',
            index=models.Index(fields=['sync_status'], name='promotion_s_sync_st_5a5e74_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionusage',
            index=models.Index(fields=['promotion', 'usage_date'], name='promotion_u_promoti_545176_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionusage',
            index=models.Index(fields=['promotion', 'customer_id', 'usage_date'], name='promotion_u_promoti_46b73c_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionusage',
            index=models.Index(fields=['transaction_id'], name='promotion_u_transac_53868e_idx'),
        ),
    ]
