# Generated by Django 6.0.1 on 2026-01-17 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('pos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('promo_type', models.CharField(choices=[('percent_discount', 'Percent Discount'), ('amount_discount', 'Amount Discount'), ('buy_x_get_y', 'Buy X Get Y'), ('combo', 'Combo Price'), ('free_item', 'Free Item')], max_length=20)),
                ('apply_to', models.CharField(choices=[('all', 'All Products'), ('category', 'Specific Category'), ('product', 'Specific Product'), ('bill', 'Entire Bill')], default='all', max_length=20)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('buy_quantity', models.IntegerField(default=0)),
                ('get_quantity', models.IntegerField(default=0)),
                ('combo_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('valid_days', models.JSONField(blank=True, default=list)),
                ('valid_time_start', models.TimeField(blank=True, null=True)),
                ('valid_time_end', models.TimeField(blank=True, null=True)),
                ('max_uses', models.IntegerField(default=0)),
                ('max_uses_per_customer', models.IntegerField(default=0)),
                ('current_uses', models.IntegerField(default=0)),
                ('min_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('min_quantity', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_auto_apply', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, to='core.category')),
                ('combo_products', models.ManyToManyField(blank=True, related_name='combo_promos', to='core.product')),
                ('get_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_promos', to='core.product')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='core.outlet')),
                ('products', models.ManyToManyField(blank=True, related_name='promos', to='core.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('qr_code', models.ImageField(blank=True, upload_to='vouchers/')),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='promotions.promotion')),
                ('used_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.bill')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applied_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_promos', to='pos.bill')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='promotions.promotion')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotions.voucher')),
            ],
        ),
    ]
