# Generated by Django 5.2.10 on 2026-01-31 15:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('floor_width', models.IntegerField(blank=True, null=True)),
                ('floor_height', models.IntegerField(blank=True, null=True)),
                ('floor_image', models.ImageField(blank=True, upload_to='floor_plans/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='core.brand')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_areas', to='core.company')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_areas', to='core.store')),
            ],
            options={
                'db_table': 'tables_tablearea',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=20)),
                ('capacity', models.IntegerField(default=4)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('billing', 'Billing'), ('dirty', 'Needs Cleaning')], default='available', max_length=20)),
                ('qr_code', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('pos_x', models.IntegerField(blank=True, null=True)),
                ('pos_y', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='tables.tablearea')),
            ],
            options={
                'db_table': 'tables_table',
                'ordering': ['area', 'number'],
            },
        ),
        migrations.CreateModel(
            name='TableGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.brand')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('main_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_groups', to='tables.table')),
            ],
            options={
                'db_table': 'tables_tablegroup',
            },
        ),
        migrations.AddField(
            model_name='table',
            name='table_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='tables.tablegroup'),
        ),
        migrations.AddIndex(
            model_name='tablearea',
            index=models.Index(fields=['brand', 'is_active'], name='tables_tabl_brand_i_bf629a_idx'),
        ),
        migrations.AddIndex(
            model_name='tablearea',
            index=models.Index(fields=['company', 'is_active'], name='tables_tabl_company_3a828f_idx'),
        ),
        migrations.AddIndex(
            model_name='tablearea',
            index=models.Index(fields=['store', 'is_active'], name='tables_tabl_store_i_924cd0_idx'),
        ),
        migrations.AddIndex(
            model_name='tablegroup',
            index=models.Index(fields=['brand', 'created_at'], name='tables_tabl_brand_i_46b1c0_idx'),
        ),
        migrations.AddIndex(
            model_name='tablegroup',
            index=models.Index(fields=['main_table'], name='tables_tabl_main_ta_c04b50_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['area', 'is_active'], name='tables_tabl_area_id_cfc5e5_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['number'], name='tables_tabl_number_bbb3e2_idx'),
        ),
    ]
