# Generated by Django 6.0.1 on 2026-01-17 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='core.outlet')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('capacity', models.IntegerField(default=4)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('billing', 'Billing'), ('dirty', 'Needs Cleaning')], default='available', max_length=20)),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/')),
                ('pos_x', models.IntegerField(default=0)),
                ('pos_y', models.IntegerField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='tables.tablearea')),
            ],
            options={
                'ordering': ['area', 'number'],
            },
        ),
        migrations.CreateModel(
            name='TableGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('main_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_groups', to='tables.table')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.outlet')),
            ],
        ),
        migrations.AddField(
            model_name='table',
            name='table_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='tables.tablegroup'),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('number', 'area')},
        ),
    ]
