# Generated by Django 5.2.11 on 2026-02-13 21:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('pos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=20)),
                ('capacity', models.IntegerField(default=4)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('billing', 'Billing'), ('dirty', 'Needs Cleaning')], default='available', max_length=20)),
                ('qr_code', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('pos_x', models.IntegerField(blank=True, null=True)),
                ('pos_y', models.IntegerField(blank=True, null=True)),
                ('shape', models.CharField(default='rect', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tables_table',
                'ordering': ['area', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reservation_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('type', models.CharField(choices=[('standard', 'Standard'), ('min_spend', 'Minimum Spend'), ('event', 'Event / Private Dining')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('deposit_pending', 'Deposit Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('reservation_date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('duration_minutes', models.IntegerField(default=120)),
                ('guest_name', models.CharField(max_length=100)),
                ('guest_phone', models.CharField(blank=True, default='', max_length=20)),
                ('guest_email', models.CharField(blank=True, default='', max_length=100)),
                ('party_size', models.IntegerField(default=2)),
                ('minimum_spend', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit_required', models.BooleanField(default=False)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit_status', models.CharField(choices=[('none', 'No Deposit'), ('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial'), ('refunded', 'Refunded'), ('forfeited', 'Forfeited')], default='none', max_length=20)),
                ('special_requests', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('noshow_at', models.DateTimeField(blank=True, null=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='pos.bill')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.brand')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.company')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_confirmed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_created', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='core.member')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.store')),
            ],
            options={
                'db_table': 'tables_reservation',
                'ordering': ['reservation_date', 'time_start'],
            },
        ),
        migrations.CreateModel(
            name='ReservationConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_booking_enabled', models.BooleanField(default=False, help_text='Aktifkan/nonaktifkan fitur booking')),
                ('default_slot_duration', models.IntegerField(default=120, help_text='Durasi default per slot (menit)')),
                ('max_advance_days', models.IntegerField(default=30, help_text='Maks booking berapa hari ke depan')),
                ('grace_period_minutes', models.IntegerField(default=30, help_text='Toleransi keterlambatan sebelum no-show')),
                ('require_deposit', models.BooleanField(default=False, help_text='Default apakah deposit wajib')),
                ('default_deposit_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('default_deposit_value', models.DecimalField(decimal_places=2, default=50, help_text='Nilai deposit (50 = 50% atau Rp 50.000)', max_digits=12)),
                ('min_deposit_amount', models.DecimalField(decimal_places=2, default=50000, help_text='Minimum deposit amount', max_digits=12)),
                ('cancellation_hours', models.IntegerField(default=24, help_text='Batas jam pembatalan tanpa penalty')),
                ('cancellation_fee_pct', models.DecimalField(decimal_places=2, default=0, help_text='Persentase penalty pembatalan', max_digits=5)),
                ('auto_noshow_minutes', models.IntegerField(default=0, help_text='0 = manual no-show only')),
                ('overbooking_buffer', models.IntegerField(default=30, help_text='Buffer menit antar booking di meja yang sama')),
                ('max_party_size', models.IntegerField(default=50, help_text='Max tamu per booking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_config', to='core.store')),
            ],
            options={
                'db_table': 'tables_reservation_config',
            },
        ),
        migrations.CreateModel(
            name='ReservationLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('confirmed', 'Confirmed'), ('deposit_paid', 'Deposit Paid'), ('checked_in', 'Checked In'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('modified', 'Modified')], max_length=30)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tables.reservation')),
            ],
            options={
                'db_table': 'tables_reservation_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('min_pax', models.IntegerField(default=1)),
                ('max_pax', models.IntegerField(default=50)),
                ('price_per_pax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fixed_price', models.DecimalField(decimal_places=2, default=0, help_text='Harga flat (alternatif per-pax)', max_digits=12)),
                ('includes_menu', models.BooleanField(default=False)),
                ('menu_items', models.JSONField(blank=True, default=list, help_text='Daftar menu yang termasuk')),
                ('duration_hours', models.IntegerField(default=3)),
                ('deposit_percentage', models.DecimalField(decimal_places=2, default=50, help_text='Override deposit % untuk paket ini', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_packages', to='core.brand')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_packages', to='core.company')),
            ],
            options={
                'db_table': 'tables_reservation_package',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='tables.reservationpackage'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='tables',
            field=models.ManyToManyField(blank=True, related_name='reservations', to='tables.table'),
        ),
        migrations.CreateModel(
            name='TableArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('floor_width', models.IntegerField(blank=True, null=True)),
                ('floor_height', models.IntegerField(blank=True, null=True)),
                ('floor_image', models.ImageField(blank=True, upload_to='floor_plans/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='core.brand')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_areas', to='core.company')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_areas', to='core.store')),
            ],
            options={
                'db_table': 'tables_tablearea',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='table',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='tables.tablearea'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='table_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='tables.tablearea'),
        ),
        migrations.CreateModel(
            name='TableGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.brand')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('main_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_groups', to='tables.table')),
            ],
            options={
                'db_table': 'tables_tablegroup',
            },
        ),
        migrations.AddField(
            model_name='table',
            name='table_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='tables.tablegroup'),
        ),
        migrations.CreateModel(
            name='ReservationDeposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('refunded', 'Refunded'), ('forfeited', 'Forfeited')], default='paid', max_length=20)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refund_reason', models.TextField(blank=True, default='')),
                ('receipt_number', models.CharField(blank=True, default='', max_length=50)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_deposits_created', to=settings.AUTH_USER_MODEL)),
                ('payment_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_deposits', to='core.paymentmethodprofile')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='tables.reservation')),
            ],
            options={
                'db_table': 'tables_reservation_deposit',
                'ordering': ['-paid_at'],
                'indexes': [models.Index(fields=['reservation', 'status'], name='tables_rese_reserva_dd6a31_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='reservationpackage',
            index=models.Index(fields=['brand', 'is_active'], name='tables_rese_brand_i_50300c_idx'),
        ),
        migrations.AddIndex(
            model_name='tablearea',
            index=models.Index(fields=['brand', 'is_active'], name='tables_tabl_brand_i_bf629a_idx'),
        ),
        migrations.AddIndex(
            model_name='tablearea',
            index=models.Index(fields=['company', 'is_active'], name='tables_tabl_company_3a828f_idx'),
        ),
        migrations.AddIndex(
            model_name='tablearea',
            index=models.Index(fields=['store', 'is_active'], name='tables_tabl_store_i_924cd0_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['brand', 'store', 'reservation_date'], name='tables_rese_brand_i_ccece8_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status', 'reservation_date'], name='tables_rese_status_8a1795_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['reservation_code'], name='tables_rese_reserva_625ac5_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['guest_phone'], name='tables_rese_guest_p_02e820_idx'),
        ),
        migrations.AddIndex(
            model_name='tablegroup',
            index=models.Index(fields=['brand', 'created_at'], name='tables_tabl_brand_i_46b1c0_idx'),
        ),
        migrations.AddIndex(
            model_name='tablegroup',
            index=models.Index(fields=['main_table'], name='tables_tabl_main_ta_c04b50_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['area', 'is_active'], name='tables_tabl_area_id_cfc5e5_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['number'], name='tables_tabl_number_bbb3e2_idx'),
        ),
    ]
