# Generated by Django 6.0.1 on 2026-01-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['area', 'sort_order', 'number']},
        ),
        migrations.AddField(
            model_name='table',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
