# Generated by Django 6.0.1 on 2026-01-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_scope',
            field=models.CharField(choices=[('store', 'Store Level'), ('brand', 'Brand Level'), ('company', 'Company Level')], default='store', help_text='Scope of authority: store manager vs area manager vs HO admin', max_length=20),
        ),
    ]
