# Generated by Django 6.0.1 on 2026-01-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_role_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='point_expiry_months_override',
            field=models.IntegerField(blank=True, help_text='Override company point expiry policy for this brand (null = use company default)', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='point_expiry_months',
            field=models.IntegerField(default=12, help_text='Points expire after X months (0 = never expire)'),
        ),
        migrations.AddField(
            model_name='company',
            name='points_per_currency',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Points earned per currency unit (e.g., 1.00 = 1 point per Rp 1)', max_digits=10),
        ),
    ]
