# Generated by Django 5.2.10 on 2026-01-29 12:03

import uuid
from django.db import migrations, models


def migrate_category_and_product_ids(apps, schema_editor):
    """Convert Category.id and Product.category_id from BigAutoField to UUID"""
    
    # Step 1: Drop foreign key constraints that reference Category.id
    try:
        schema_editor.execute(
            'ALTER TABLE core_category DROP CONSTRAINT IF EXISTS core_category_parent_id_f82a0951_fk_core_category_id CASCADE;'
        )
    except Exception:
        pass
        
    try:
        schema_editor.execute(
            'ALTER TABLE core_product DROP CONSTRAINT IF EXISTS core_product_category_id_b9d8ff9f_fk_core_category_id CASCADE;'
        )
    except Exception:
        pass

    # Step 2: Add new UUID columns
    schema_editor.execute(
        'ALTER TABLE core_category ADD COLUMN IF NOT EXISTS id_new uuid;'
    )
    schema_editor.execute(
        'ALTER TABLE core_category ADD COLUMN IF NOT EXISTS parent_id_new uuid;'
    )
    schema_editor.execute(
        'ALTER TABLE core_product ADD COLUMN IF NOT EXISTS category_id_new uuid;'
    )

    # Step 3: Generate UUID values for new columns
    schema_editor.execute(
        'UPDATE core_category SET id_new = gen_random_uuid() WHERE id_new IS NULL;'
    )

    # Step 4: Map parent_id references to new UUID values
    schema_editor.execute(
        '''UPDATE core_category c1 
           SET parent_id_new = c2.id_new 
           FROM core_category c2 
           WHERE c1.parent_id = c2.id AND c1.parent_id IS NOT NULL;'''
    )

    # Step 5: Map category_id references to new UUID values
    schema_editor.execute(
        '''UPDATE core_product p 
           SET category_id_new = c.id_new 
           FROM core_category c 
           WHERE p.category_id = c.id AND p.category_id IS NOT NULL;'''
    )

    # Step 6: Drop primary key constraint
    schema_editor.execute(
        'ALTER TABLE core_category DROP CONSTRAINT core_category_pkey CASCADE;'
    )

    # Step 7: Drop old columns
    schema_editor.execute(
        'ALTER TABLE core_category DROP COLUMN id CASCADE;'
    )
    schema_editor.execute(
        'ALTER TABLE core_category DROP COLUMN parent_id CASCADE;'
    )
    schema_editor.execute(
        'ALTER TABLE core_product DROP COLUMN category_id CASCADE;'
    )

    # Step 8: Rename new columns to original names
    schema_editor.execute(
        'ALTER TABLE core_category RENAME COLUMN id_new TO id;'
    )
    schema_editor.execute(
        'ALTER TABLE core_category RENAME COLUMN parent_id_new TO parent_id;'
    )
    schema_editor.execute(
        'ALTER TABLE core_product RENAME COLUMN category_id_new TO category_id;'
    )

    # Step 9: Add primary key back
    schema_editor.execute(
        'ALTER TABLE core_category ADD PRIMARY KEY (id);'
    )

    # Step 10: Recreate foreign key constraints
    schema_editor.execute(
        '''ALTER TABLE core_category 
           ADD CONSTRAINT core_category_parent_id_f82a0951_fk_core_category_id 
           FOREIGN KEY (parent_id) REFERENCES core_category(id) ON DELETE SET NULL;'''
    )
    
    schema_editor.execute(
        '''ALTER TABLE core_product 
           ADD CONSTRAINT core_product_category_id_b9d8ff9f_fk_core_category_id 
           FOREIGN KEY (category_id) REFERENCES core_category(id) ON DELETE SET NULL;'''
    )


def reverse_migrate(apps, schema_editor):
    """Reverse migration - not safely reversible"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_multi_brand_store'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='storebrand',
            name='unique_store_brand',
        ),
        migrations.RunPython(migrate_category_and_product_ids, reverse_migrate),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=models.SET_NULL, related_name='products', to='core.category'),
        ),
        migrations.AlterUniqueTogether(
            name='storebrand',
            unique_together={('store', 'brand')},
        ),
    ]
