# Generated by Django 5.2.10 on 2026-01-30 00:00

import uuid
from django.db import migrations, models


def migrate_product_and_modifier_ids(apps, schema_editor):
    """Convert core_product/core_modifier IDs to UUID and update core references."""
    schema_editor.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto;")

    # Preserve legacy bigint IDs for downstream mapping
    schema_editor.execute("ALTER TABLE core_product ADD COLUMN IF NOT EXISTS legacy_id bigint;")
    schema_editor.execute("UPDATE core_product SET legacy_id = id WHERE legacy_id IS NULL;")
    schema_editor.execute("ALTER TABLE core_modifier ADD COLUMN IF NOT EXISTS legacy_id bigint;")
    schema_editor.execute("UPDATE core_modifier SET legacy_id = id WHERE legacy_id IS NULL;")

    # Add new UUID primary key columns
    schema_editor.execute("ALTER TABLE core_product ADD COLUMN IF NOT EXISTS id_new uuid;")
    schema_editor.execute("UPDATE core_product SET id_new = gen_random_uuid() WHERE id_new IS NULL;")
    schema_editor.execute("ALTER TABLE core_modifier ADD COLUMN IF NOT EXISTS id_new uuid;")
    schema_editor.execute("UPDATE core_modifier SET id_new = gen_random_uuid() WHERE id_new IS NULL;")

    # Modifier option id + FK to modifier
    schema_editor.execute("ALTER TABLE core_modifieroption ADD COLUMN IF NOT EXISTS id_new uuid;")
    schema_editor.execute("UPDATE core_modifieroption SET id_new = gen_random_uuid() WHERE id_new IS NULL;")
    schema_editor.execute("ALTER TABLE core_modifieroption ADD COLUMN IF NOT EXISTS modifier_id_new uuid;")

    # Core tables that reference product/modifier
    schema_editor.execute("ALTER TABLE core_productphoto ADD COLUMN IF NOT EXISTS product_id_new uuid;")
    schema_editor.execute("ALTER TABLE core_modifier_products ADD COLUMN IF NOT EXISTS modifier_id_new uuid;")
    schema_editor.execute("ALTER TABLE core_modifier_products ADD COLUMN IF NOT EXISTS product_id_new uuid;")

    schema_editor.execute(
        """UPDATE core_modifieroption mo
           SET modifier_id_new = m.id_new
           FROM core_modifier m
           WHERE mo.modifier_id = m.legacy_id;"""
    )
    schema_editor.execute(
        """UPDATE core_productphoto pp
           SET product_id_new = p.id_new
           FROM core_product p
           WHERE pp.product_id = p.legacy_id;"""
    )
    schema_editor.execute(
        """UPDATE core_modifier_products mp
           SET modifier_id_new = m.id_new
           FROM core_modifier m
           WHERE mp.modifier_id = m.legacy_id;"""
    )
    schema_editor.execute(
        """UPDATE core_modifier_products mp
           SET product_id_new = p.id_new
           FROM core_product p
           WHERE mp.product_id = p.legacy_id;"""
    )

    # Drop old PKs and columns (cascade removes FK constraints)
    schema_editor.execute("ALTER TABLE core_product DROP CONSTRAINT IF EXISTS core_product_pkey CASCADE;")
    schema_editor.execute("ALTER TABLE core_modifier DROP CONSTRAINT IF EXISTS core_modifier_pkey CASCADE;")
    schema_editor.execute("ALTER TABLE core_modifieroption DROP CONSTRAINT IF EXISTS core_modifieroption_pkey CASCADE;")

    schema_editor.execute("ALTER TABLE core_product DROP COLUMN id CASCADE;")
    schema_editor.execute("ALTER TABLE core_modifier DROP COLUMN id CASCADE;")
    schema_editor.execute("ALTER TABLE core_modifieroption DROP COLUMN id CASCADE;")
    schema_editor.execute("ALTER TABLE core_modifieroption DROP COLUMN modifier_id CASCADE;")
    schema_editor.execute("ALTER TABLE core_productphoto DROP COLUMN product_id CASCADE;")
    schema_editor.execute("ALTER TABLE core_modifier_products DROP COLUMN modifier_id CASCADE;")
    schema_editor.execute("ALTER TABLE core_modifier_products DROP COLUMN product_id CASCADE;")

    # Rename new columns
    schema_editor.execute("ALTER TABLE core_product RENAME COLUMN id_new TO id;")
    schema_editor.execute("ALTER TABLE core_modifier RENAME COLUMN id_new TO id;")
    schema_editor.execute("ALTER TABLE core_modifieroption RENAME COLUMN id_new TO id;")
    schema_editor.execute("ALTER TABLE core_modifieroption RENAME COLUMN modifier_id_new TO modifier_id;")
    schema_editor.execute("ALTER TABLE core_productphoto RENAME COLUMN product_id_new TO product_id;")
    schema_editor.execute("ALTER TABLE core_modifier_products RENAME COLUMN modifier_id_new TO modifier_id;")
    schema_editor.execute("ALTER TABLE core_modifier_products RENAME COLUMN product_id_new TO product_id;")

    # Recreate PK and FK constraints
    schema_editor.execute("ALTER TABLE core_product ADD PRIMARY KEY (id);")
    schema_editor.execute("ALTER TABLE core_modifier ADD PRIMARY KEY (id);")
    schema_editor.execute("ALTER TABLE core_modifieroption ADD PRIMARY KEY (id);")

    schema_editor.execute(
        """ALTER TABLE core_modifieroption
           ADD CONSTRAINT core_modifieroption_modifier_id_fk
           FOREIGN KEY (modifier_id) REFERENCES core_modifier(id) ON DELETE CASCADE;"""
    )
    schema_editor.execute(
        """ALTER TABLE core_productphoto
           ADD CONSTRAINT core_productphoto_product_id_fk
           FOREIGN KEY (product_id) REFERENCES core_product(id) ON DELETE CASCADE;"""
    )
    schema_editor.execute(
        """ALTER TABLE core_modifier_products
           ADD CONSTRAINT core_modifier_products_modifier_id_fk
           FOREIGN KEY (modifier_id) REFERENCES core_modifier(id) ON DELETE CASCADE;"""
    )
    schema_editor.execute(
        """ALTER TABLE core_modifier_products
           ADD CONSTRAINT core_modifier_products_product_id_fk
           FOREIGN KEY (product_id) REFERENCES core_product(id) ON DELETE CASCADE;"""
    )
    schema_editor.execute(
        """ALTER TABLE core_modifier_products
           ADD CONSTRAINT core_modifier_products_modifier_id_product_id_uniq
           UNIQUE (modifier_id, product_id);"""
    )


def reverse_migrate(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_storebrand_unique_store_brand_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(migrate_product_and_modifier_ids, reverse_migrate),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='product',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='modifier',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='modifieroption',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
