# Generated by Django 5.2.10 on 2026-01-30 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_convert_product_id_to_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifier',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modifier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modifier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
