# Generated by Django 5.2.10 on 2026-01-30 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


def create_tables_with_proper_schema(apps, schema_editor):
    """Recreate modifier tables with HO-compatible schema"""
    schema_editor.execute("""
        CREATE TABLE IF NOT EXISTS core_modifier (
            id uuid NOT NULL PRIMARY KEY,
            name varchar(200) NOT NULL,
            is_required boolean NOT NULL,
            max_selections integer NOT NULL,
            is_active boolean NOT NULL,
            created_at timestamptz NOT NULL,
            updated_at timestamptz NOT NULL,
            brand_id uuid NOT NULL,
            CONSTRAINT core_modifier_brand_id_fk FOREIGN KEY (brand_id) REFERENCES core_brand(id) DEFERRABLE INITIALLY DEFERRED
        );
        CREATE INDEX IF NOT EXISTS core_modifier_brand_id_idx ON core_modifier(brand_id);
        CREATE INDEX IF NOT EXISTS core_modifier_brand_i_e84568_idx ON core_modifier(brand_id, is_active);

        CREATE TABLE IF NOT EXISTS core_modifier_option (
            id uuid NOT NULL PRIMARY KEY,
            name varchar(200) NOT NULL,
            price_adjustment numeric(10, 2) NOT NULL,
            is_default boolean NOT NULL,
            sort_order integer NOT NULL,
            is_active boolean NOT NULL,
            created_at timestamptz NOT NULL,
            modifier_id uuid NOT NULL,
            CONSTRAINT core_modifieroption_modifier_id_fk FOREIGN KEY (modifier_id) REFERENCES core_modifier(id) DEFERRABLE INITIALLY DEFERRED
        );
        CREATE INDEX IF NOT EXISTS core_modifieroption_modifier_id_idx ON core_modifier_option(modifier_id);
        CREATE INDEX IF NOT EXISTS core_modifi_modifie_a1879c_idx ON core_modifier_option(modifier_id, is_active);

        CREATE TABLE IF NOT EXISTS core_product_modifier (
            id uuid NOT NULL PRIMARY KEY,
            sort_order integer NOT NULL,
            modifier_id uuid NOT NULL,
            product_id uuid NOT NULL,
            CONSTRAINT core_product_modifier_modifier_id_fk FOREIGN KEY (modifier_id) REFERENCES core_modifier(id) DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT core_product_modifier_product_id_fk FOREIGN KEY (product_id) REFERENCES core_product(id) DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT core_product_modifier_product_id_modifier_id_uniq UNIQUE (product_id, modifier_id)
        );
        CREATE INDEX IF NOT EXISTS core_product_mod_product_76c6c8_idx ON core_product_modifier(product_id);
        CREATE INDEX IF NOT EXISTS core_product_mod_modifie_2780a0_idx ON core_product_modifier(modifier_id);
    """)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_modifier_missing_fields'),
    ]

    operations = [
        migrations.RunPython(create_tables_with_proper_schema, reverse_func),
    ]
