# Generated by Django 5.2.10 on 2026-01-30 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_recreate_modifier_tables_ho_compatible'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='ProductModifier',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('sort_order', models.IntegerField(default=0)),
                        ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_modifiers', to='core.modifier')),
                        ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_modifiers', to='core.product')),
                    ],
                    options={
                        'db_table': 'core_product_modifier',
                    },
                ),
                    migrations.AddConstraint(
                        model_name='productmodifier',
                        constraint=models.UniqueConstraint(fields=['product', 'modifier'], name='core_productmodifier_product_modifier_unique'),
                    ),
                    migrations.AddIndex(
                        model_name='productmodifier',
                        index=models.Index(fields=['product'], name='core_product_mod_product_76c6c8_idx'),
                    ),
                    migrations.AddIndex(
                        model_name='productmodifier',
                        index=models.Index(fields=['modifier'], name='core_product_mod_modifie_2780a0_idx'),
                    ),
            ]
        ),
    ]
