# Generated by Django 5.2.10 on 2026-01-31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_product_modifier_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('brand', 'category', 'name', 'sku')},
        ),
    ]
