# Generated by Django 5.2.10 on 2026-02-04 13:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('member_code', models.CharField(blank=True, help_text='Member ID/Code from external CRM', max_length=50)),
                ('member_name', models.CharField(blank=True, help_text='Member name for display', max_length=200)),
                ('bill_type', models.CharField(choices=[('dine_in', 'Dine In'), ('takeaway', 'Take Away'), ('delivery', 'Delivery')], default='dine_in', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('hold', 'On Hold'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('void', 'Voided')], default='open', max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('guest_count', models.IntegerField(default=1)),
                ('queue_number', models.IntegerField(blank=True, help_text='Auto-increment daily for takeaway orders', null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_type', models.CharField(blank=True, max_length=20)),
                ('discount_reference', models.CharField(blank=True, max_length=100)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When order was picked up by customer', null=True)),
                ('notes', models.TextField(blank=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='core.brand')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_closed', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, help_text='Denormalized for reporting performance', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='core.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills_created', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='core.store')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='tables.table')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='core.posterminal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('modifier_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('modifiers', models.JSONField(blank=True, default=list)),
                ('printer_target', models.CharField(blank=True, help_text='Kitchen station code for printer routing (e.g., BAR, KITCHEN, DESSERT)', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent to Kitchen'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('served', 'Served')], default='pending', max_length=20)),
                ('is_void', models.BooleanField(default=False)),
                ('void_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('split_group', models.IntegerField(default=0)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.bill')),
                ('brand', models.ForeignKey(blank=True, help_text='Denormalized for product analytics', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.brand')),
                ('company', models.ForeignKey(blank=True, help_text='Denormalized for product analytics', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_items_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
                ('void_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('open', 'Bill Opened'), ('add_item', 'Item Added'), ('void_item', 'Item Voided'), ('update_qty', 'Quantity Updated'), ('hold', 'Bill Held'), ('resume', 'Bill Resumed'), ('send_kitchen', 'Sent to Kitchen'), ('payment', 'Payment Made'), ('close', 'Bill Closed'), ('completed', 'Order Completed'), ('cancel', 'Bill Cancelled'), ('discount', 'Discount Applied'), ('reprint_receipt', 'Receipt Reprinted'), ('reprint_kitchen', 'Kitchen Order Reprinted'), ('split_bill', 'Bill Split'), ('merge_bill', 'Bill Merged'), ('move_table', 'Table Moved')], max_length=30)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='pos.bill')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('refund_type', models.CharField(choices=[('full', 'Full Refund'), ('partial', 'Partial Refund')], max_length=20)),
                ('reason', models.CharField(choices=[('wrong_order', 'Wrong Order / Input Error'), ('customer_complaint', 'Customer Complaint'), ('quality_issue', 'Quality Issue'), ('service_issue', 'Service Issue'), ('price_error', 'Price Error'), ('duplicate_payment', 'Duplicate Payment'), ('cancelled_late', 'Cancelled After Payment'), ('other', 'Other')], max_length=30)),
                ('reason_notes', models.TextField(blank=True, help_text='Detailed explanation')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('original_total', models.DecimalField(decimal_places=2, help_text='Original bill total', max_digits=12)),
                ('refund_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refund_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refund_service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refund_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approval_pin', models.CharField(blank=True, max_length=6)),
                ('approval_notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('original_payments', models.JSONField(default=dict, help_text='Original payment methods and amounts')),
                ('refund_payments', models.JSONField(default=dict, help_text='How refund was processed per payment method')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_approved', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_completed', to=settings.AUTH_USER_MODEL)),
                ('original_bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='pos.bill')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='BillRefundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_quantity', models.IntegerField()),
                ('refund_quantity', models.IntegerField()),
                ('refund_reason', models.CharField(blank=True, max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('original_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.billitem')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunded_items', to='pos.billrefund')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('qris', 'QRIS'), ('transfer', 'Bank Transfer'), ('ewallet', 'E-Wallet'), ('voucher', 'Voucher')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pos.bill')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_processed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('terminal_id', models.CharField(help_text='Target terminal/cashier ID', max_length=50)),
                ('job_type', models.CharField(choices=[('receipt', 'Customer Receipt'), ('kitchen', 'Kitchen Order'), ('report', 'Report'), ('reprint', 'Reprint')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fetched', 'Fetched'), ('printing', 'Printing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('content', models.JSONField(help_text='Print job data (bill info, items, etc)')),
                ('fetched_at', models.DateTimeField(blank=True, help_text='When agent picked up the job', null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='pos.bill')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundPaymentReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=20)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, help_text='Refund transaction reference', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('original_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.payment')),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_reversals', to='pos.billrefund')),
            ],
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['company', 'created_at'], name='pos_bill_company_d5c516_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['company', 'status', 'created_at'], name='pos_bill_company_9d6550_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['brand', 'store', 'status', 'created_at'], name='pos_bill_brand_i_8f96de_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['store', 'created_at'], name='pos_bill_store_i_b0b4d3_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['table', 'status'], name='pos_bill_table_i_9c3bdc_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['member_code', 'created_at'], name='pos_bill_member__6e618f_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['brand', 'bill_type', 'created_at'], name='pos_bill_brand_i_52b3d3_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['created_by', 'created_at'], name='pos_bill_created_dcb016_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['closed_by', 'closed_at'], name='pos_bill_closed__bba015_idx'),
        ),
        migrations.AddIndex(
            model_name='billitem',
            index=models.Index(fields=['bill', 'is_void', 'status'], name='pos_billite_bill_id_a4ee28_idx'),
        ),
        migrations.AddIndex(
            model_name='billitem',
            index=models.Index(fields=['created_by', 'created_at'], name='pos_billite_created_94bdef_idx'),
        ),
        migrations.AddIndex(
            model_name='billitem',
            index=models.Index(fields=['company', 'product', 'created_at'], name='pos_billite_company_ac654a_idx'),
        ),
        migrations.AddIndex(
            model_name='billitem',
            index=models.Index(fields=['brand', 'product', 'created_at'], name='pos_billite_brand_i_d74d3b_idx'),
        ),
        migrations.AddIndex(
            model_name='billrefund',
            index=models.Index(fields=['original_bill', 'status'], name='pos_billref_origina_6049dd_idx'),
        ),
        migrations.AddIndex(
            model_name='billrefund',
            index=models.Index(fields=['refund_number'], name='pos_billref_refund__2528a3_idx'),
        ),
        migrations.AddIndex(
            model_name='billrefund',
            index=models.Index(fields=['status', 'requested_at'], name='pos_billref_status_d44c2f_idx'),
        ),
        migrations.AddIndex(
            model_name='billrefund',
            index=models.Index(fields=['requested_by', 'requested_at'], name='pos_billref_request_94b99d_idx'),
        ),
        migrations.AddIndex(
            model_name='billrefunditem',
            index=models.Index(fields=['refund', 'original_item'], name='pos_billref_refund__0586da_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['bill', 'created_at'], name='pos_payment_bill_id_93adca_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_by', 'created_at'], name='pos_payment_created_1d77c2_idx'),
        ),
        migrations.AddIndex(
            model_name='printjob',
            index=models.Index(fields=['terminal_id', 'status', 'created_at'], name='pos_printjo_termina_ebe342_idx'),
        ),
        migrations.AddIndex(
            model_name='printjob',
            index=models.Index(fields=['job_uuid'], name='pos_printjo_job_uui_780151_idx'),
        ),
        migrations.AddIndex(
            model_name='refundpaymentreversal',
            index=models.Index(fields=['refund', 'payment_method'], name='pos_refundp_refund__437049_idx'),
        ),
        migrations.AddIndex(
            model_name='refundpaymentreversal',
            index=models.Index(fields=['original_payment'], name='pos_refundp_origina_c07fe9_idx'),
        ),
    ]
