# Generated by Django 5.2.11 on 2026-02-13 21:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('modifier_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('modifiers', models.JSONField(blank=True, default=list)),
                ('printer_target', models.CharField(blank=True, help_text='Kitchen station code for printer routing (e.g., BAR, KITCHEN, DESSERT)', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent to Kitchen'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('served', 'Served')], default='pending', max_length=20)),
                ('is_void', models.BooleanField(default=False)),
                ('void_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('split_group', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BillLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('open', 'Bill Opened'), ('add_item', 'Item Added'), ('void_item', 'Item Voided'), ('update_qty', 'Quantity Updated'), ('hold', 'Bill Held'), ('resume', 'Bill Resumed'), ('send_kitchen', 'Sent to Kitchen'), ('payment', 'Payment Made'), ('close', 'Bill Closed'), ('completed', 'Order Completed'), ('cancel', 'Bill Cancelled'), ('discount', 'Discount Applied'), ('reprint_receipt', 'Receipt Reprinted'), ('reprint_kitchen', 'Kitchen Order Reprinted'), ('split_bill', 'Bill Split'), ('merge_bill', 'Bill Merged'), ('move_table', 'Table Moved')], max_length=30)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('refund_type', models.CharField(choices=[('full', 'Full Refund'), ('partial', 'Partial Refund')], max_length=20)),
                ('reason', models.CharField(choices=[('wrong_order', 'Wrong Order / Input Error'), ('customer_complaint', 'Customer Complaint'), ('quality_issue', 'Quality Issue'), ('service_issue', 'Service Issue'), ('price_error', 'Price Error'), ('duplicate_payment', 'Duplicate Payment'), ('cancelled_late', 'Cancelled After Payment'), ('other', 'Other')], max_length=30)),
                ('reason_notes', models.TextField(blank=True, help_text='Detailed explanation')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('original_total', models.DecimalField(decimal_places=2, help_text='Original bill total', max_digits=12)),
                ('refund_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refund_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refund_service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refund_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approval_pin', models.CharField(blank=True, max_length=6)),
                ('approval_notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('original_payments', models.JSONField(default=dict, help_text='Original payment methods and amounts')),
                ('refund_payments', models.JSONField(default=dict, help_text='How refund was processed per payment method')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='BillRefundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_quantity', models.IntegerField()),
                ('refund_quantity', models.IntegerField()),
                ('refund_reason', models.CharField(blank=True, max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('payment_metadata', models.JSONField(blank=True, default=dict, help_text='Extra data fields from prompts: {"account_no": "1234", "eft_no": "AB"}')),
                ('eft_desc', models.CharField(blank=True, help_text='Denormalized EFT terminal description, e.g. "01: BCA"', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('terminal_id', models.CharField(help_text='Target terminal/cashier ID', max_length=50)),
                ('job_type', models.CharField(choices=[('receipt', 'Customer Receipt'), ('kitchen', 'Kitchen Order'), ('report', 'Report'), ('reprint', 'Reprint')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fetched', 'Fetched'), ('printing', 'Printing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('content', models.JSONField(help_text='Print job data (bill info, items, etc)')),
                ('fetched_at', models.DateTimeField(blank=True, help_text='When agent picked up the job', null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRISAuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('create', 'QR Created'), ('status_check', 'Status Polled'), ('status_change', 'Status Changed'), ('payment_confirmed', 'Payment Confirmed'), ('expired', 'Transaction Expired'), ('cancelled', 'Transaction Cancelled'), ('auto_cancel', 'Auto-cancelled (new QR)'), ('simulate', 'Payment Simulated'), ('error', 'Error'), ('gateway_timeout', 'Gateway Timeout'), ('gateway_error', 'Gateway Error')], max_length=30)),
                ('txn_ref', models.CharField(blank=True, db_index=True, help_text='QRIS transaction_id reference', max_length=100)),
                ('status_before', models.CharField(blank=True, max_length=20)),
                ('status_after', models.CharField(blank=True, max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gateway_name', models.CharField(blank=True, max_length=50)),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Response time from gateway in milliseconds', null=True)),
                ('elapsed_since_create_s', models.FloatField(blank=True, help_text='Seconds since QR was created (wait time)', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'pos_qris_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRISTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qr_string', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('expired', 'Expired'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('gateway_name', models.CharField(default='mock', max_length=50)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pos_qris_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundPaymentReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=20)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, help_text='Refund transaction reference', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreProductStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField(db_index=True, help_text='Reference to core_product.id (not FK - may change on sync)')),
                ('product_sku', models.CharField(db_index=True, help_text='SKU from core_product', max_length=50)),
                ('product_name', models.CharField(help_text='Cached product name for display', max_length=200)),
                ('daily_stock', models.DecimalField(decimal_places=2, default=0, help_text='Opening stock for the day (set by store staff)', max_digits=10)),
                ('sold_qty', models.DecimalField(decimal_places=2, default=0, help_text='Quantity sold/sent to kitchen today', max_digits=10)),
                ('low_stock_alert', models.IntegerField(default=5, help_text='Show warning when remaining stock falls below this number')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this product is being stock-tracked')),
                ('last_reset_date', models.DateField(blank=True, help_text='Last date stock was reset/restocked', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Product Stock',
                'verbose_name_plural': 'Store Product Stocks',
                'db_table': 'pos_store_product_stock',
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('member_code', models.CharField(blank=True, help_text='Member ID/Code from external CRM', max_length=50)),
                ('member_name', models.CharField(blank=True, help_text='Member name for display', max_length=200)),
                ('bill_type', models.CharField(choices=[('dine_in', 'Dine In'), ('takeaway', 'Take Away'), ('delivery', 'Delivery')], default='dine_in', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('hold', 'On Hold'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('void', 'Voided')], default='open', max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('guest_count', models.IntegerField(default=1)),
                ('queue_number', models.IntegerField(blank=True, help_text='Auto-increment daily for takeaway orders', null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_type', models.CharField(blank=True, max_length=20)),
                ('discount_reference', models.CharField(blank=True, max_length=100)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When order was picked up by customer', null=True)),
                ('notes', models.TextField(blank=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='core.brand')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_closed', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, help_text='Denormalized for reporting performance', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='core.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills_created', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='core.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
