# Generated by Django 5.2.10 on 2026-02-11 01:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_customerdisplayconfig_brand_logo_and_more'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProductStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField(db_index=True, help_text='Reference to core_product.id (not FK - may change on sync)')),
                ('product_sku', models.CharField(db_index=True, help_text='SKU from core_product', max_length=50)),
                ('product_name', models.CharField(help_text='Cached product name for display', max_length=200)),
                ('daily_stock', models.DecimalField(decimal_places=2, default=0, help_text='Opening stock for the day (set by store staff)', max_digits=10)),
                ('sold_qty', models.DecimalField(decimal_places=2, default=0, help_text='Quantity sold/sent to kitchen today', max_digits=10)),
                ('low_stock_alert', models.IntegerField(default=5, help_text='Show warning when remaining stock falls below this number')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this product is being stock-tracked')),
                ('last_reset_date', models.DateField(blank=True, help_text='Last date stock was reset/restocked', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(help_text='Brand this stock record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='store_stocks', to='core.brand')),
            ],
            options={
                'verbose_name': 'Store Product Stock',
                'verbose_name_plural': 'Store Product Stocks',
                'db_table': 'pos_store_product_stock',
                'ordering': ['product_name'],
                'indexes': [models.Index(fields=['brand', 'is_active'], name='pos_store_p_brand_i_be3b7f_idx'), models.Index(fields=['product_id'], name='pos_store_p_product_248d71_idx')],
                'unique_together': {('product_sku', 'brand')},
            },
        ),
    ]
