# Generated by Django 5.2.11 on 2026-02-13 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('pos', '0001_initial'),
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='tables.table'),
        ),
        migrations.AddField(
            model_name='bill',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='core.posterminal'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.bill'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Denormalized for product analytics', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.brand'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Denormalized for product analytics', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.company'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_items_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='void_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billlog',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='pos.bill'),
        ),
        migrations.AddField(
            model_name='billlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billrefund',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billrefund',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billrefund',
            name='original_bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='pos.bill'),
        ),
        migrations.AddField(
            model_name='billrefund',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billrefunditem',
            name='original_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.billitem'),
        ),
        migrations.AddField(
            model_name='billrefunditem',
            name='refund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunded_items', to='pos.billrefund'),
        ),
        migrations.AddField(
            model_name='payment',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pos.bill'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_processed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_profile',
            field=models.ForeignKey(blank=True, help_text='Payment method profile used (null for legacy payments)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.paymentmethodprofile'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='pos.bill'),
        ),
        migrations.AddField(
            model_name='qrisauditlog',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qris_audit_logs', to='pos.bill'),
        ),
        migrations.AddField(
            model_name='qrisauditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qristransaction',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qris_transactions', to='pos.bill'),
        ),
        migrations.AddField(
            model_name='qristransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qris_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qrisauditlog',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='pos.qristransaction'),
        ),
        migrations.AddField(
            model_name='refundpaymentreversal',
            name='original_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.payment'),
        ),
        migrations.AddField(
            model_name='refundpaymentreversal',
            name='processed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refundpaymentreversal',
            name='refund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_reversals', to='pos.billrefund'),
        ),
        migrations.AddField(
            model_name='storeproductstock',
            name='brand',
            field=models.ForeignKey(help_text='Brand this stock record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='store_stocks', to='core.brand'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['company', 'created_at'], name='pos_bill_company_d5c516_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['company', 'status', 'created_at'], name='pos_bill_company_9d6550_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['brand', 'store', 'status', 'created_at'], name='pos_bill_brand_i_8f96de_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['store', 'created_at'], name='pos_bill_store_i_b0b4d3_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['table', 'status'], name='pos_bill_table_i_9c3bdc_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['member_code', 'created_at'], name='pos_bill_member__6e618f_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['brand', 'bill_type', 'created_at'], name='pos_bill_brand_i_52b3d3_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['created_by', 'created_at'], name='pos_bill_created_dcb016_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['closed_by', 'closed_at'], name='pos_bill_closed__bba015_idx'),
        ),
        migrations.AddIndex(
            model_name='billitem',
            index=models.Index(fields=['bill', 'is_void', 'status'], name='pos_billite_bill_id_a4ee28_idx'),
        ),
        migrations.AddIndex(
            model_name='billitem',
            index=models.Index(fields=['created_by', 'created_at'], name='pos_billite_created_94bdef_idx'),
        ),
        migrations.AddIndex(
            model_name='billitem',
            index=models.Index(fields=['company', 'product', 'created_at'], name='pos_billite_company_ac654a_idx'),
        ),
        migrations.AddIndex(
            model_name='billitem',
            index=models.Index(fields=['brand', 'product', 'created_at'], name='pos_billite_brand_i_d74d3b_idx'),
        ),
        migrations.AddIndex(
            model_name='billrefund',
            index=models.Index(fields=['original_bill', 'status'], name='pos_billref_origina_6049dd_idx'),
        ),
        migrations.AddIndex(
            model_name='billrefund',
            index=models.Index(fields=['refund_number'], name='pos_billref_refund__2528a3_idx'),
        ),
        migrations.AddIndex(
            model_name='billrefund',
            index=models.Index(fields=['status', 'requested_at'], name='pos_billref_status_d44c2f_idx'),
        ),
        migrations.AddIndex(
            model_name='billrefund',
            index=models.Index(fields=['requested_by', 'requested_at'], name='pos_billref_request_94b99d_idx'),
        ),
        migrations.AddIndex(
            model_name='billrefunditem',
            index=models.Index(fields=['refund', 'original_item'], name='pos_billref_refund__0586da_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['bill', 'created_at'], name='pos_payment_bill_id_93adca_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_by', 'created_at'], name='pos_payment_created_1d77c2_idx'),
        ),
        migrations.AddIndex(
            model_name='printjob',
            index=models.Index(fields=['terminal_id', 'status', 'created_at'], name='pos_printjo_termina_ebe342_idx'),
        ),
        migrations.AddIndex(
            model_name='printjob',
            index=models.Index(fields=['job_uuid'], name='pos_printjo_job_uui_780151_idx'),
        ),
        migrations.AddIndex(
            model_name='qristransaction',
            index=models.Index(fields=['bill', 'status'], name='pos_qris_tr_bill_id_a9ec62_idx'),
        ),
        migrations.AddIndex(
            model_name='qristransaction',
            index=models.Index(fields=['transaction_id'], name='pos_qris_tr_transac_acc709_idx'),
        ),
        migrations.AddIndex(
            model_name='qrisauditlog',
            index=models.Index(fields=['txn_ref', 'event'], name='pos_qris_au_txn_ref_62fe6b_idx'),
        ),
        migrations.AddIndex(
            model_name='qrisauditlog',
            index=models.Index(fields=['bill', 'created_at'], name='pos_qris_au_bill_id_8a0023_idx'),
        ),
        migrations.AddIndex(
            model_name='qrisauditlog',
            index=models.Index(fields=['event', 'created_at'], name='pos_qris_au_event_6d40c3_idx'),
        ),
        migrations.AddIndex(
            model_name='refundpaymentreversal',
            index=models.Index(fields=['refund', 'payment_method'], name='pos_refundp_refund__437049_idx'),
        ),
        migrations.AddIndex(
            model_name='refundpaymentreversal',
            index=models.Index(fields=['original_payment'], name='pos_refundp_origina_c07fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='storeproductstock',
            index=models.Index(fields=['brand', 'is_active'], name='pos_store_p_brand_i_be3b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='storeproductstock',
            index=models.Index(fields=['product_id'], name='pos_store_p_product_248d71_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storeproductstock',
            unique_together={('product_sku', 'brand')},
        ),
    ]
