# Generated by Django 5.2.10 on 2026-02-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='printer_target',
            field=models.CharField(blank=True, help_text='Kitchen station code for printer routing (e.g., BAR, KITCHEN, DESSERT)', max_length=50),
        ),
    ]
