# Generated by Django 6.0.1 on 2026-01-17 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('pos', '0002_bill_terminal'),
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_processed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['created_by', 'created_at'], name='pos_bill_created_dcb016_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['closed_by', 'closed_at'], name='pos_bill_closed__bba015_idx'),
        ),
        migrations.AddIndex(
            model_name='billitem',
            index=models.Index(fields=['created_by', 'created_at'], name='pos_billite_created_94bdef_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['bill', 'created_at'], name='pos_payment_bill_id_93adca_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_by', 'created_at'], name='pos_payment_created_1d77c2_idx'),
        ),
    ]
