# Generated by Django 5.2.11 on 2026-02-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('debit', 'Debit Card'), ('qris', 'QRIS'), ('transfer', 'Bank Transfer'), ('ewallet', 'E-Wallet'), ('voucher', 'Voucher'), ('deposit', 'Deposit (Reservation)')], max_length=50),
        ),
    ]
