# Generated by Django 5.2.11 on 2026-02-12 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_payment_profiles'),
        ('pos', '0003_add_qris_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Extra data fields from prompts: {"account_no": "1234", "eft_no": "AB"}'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_profile',
            field=models.ForeignKey(blank=True, help_text='Payment method profile used (null for legacy payments)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.paymentmethodprofile'),
        ),
    ]
