# Generated by Django 5.2.11 on 2026-02-12 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_payment_eft_desc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRISAuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('create', 'QR Created'), ('status_check', 'Status Polled'), ('status_change', 'Status Changed'), ('payment_confirmed', 'Payment Confirmed'), ('expired', 'Transaction Expired'), ('cancelled', 'Transaction Cancelled'), ('auto_cancel', 'Auto-cancelled (new QR)'), ('simulate', 'Payment Simulated'), ('error', 'Error'), ('gateway_timeout', 'Gateway Timeout'), ('gateway_error', 'Gateway Error')], max_length=30)),
                ('txn_ref', models.CharField(blank=True, db_index=True, help_text='QRIS transaction_id reference', max_length=100)),
                ('status_before', models.CharField(blank=True, max_length=20)),
                ('status_after', models.CharField(blank=True, max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gateway_name', models.CharField(blank=True, max_length=50)),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Response time from gateway in milliseconds', null=True)),
                ('elapsed_since_create_s', models.FloatField(blank=True, help_text='Seconds since QR was created (wait time)', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qris_audit_logs', to='pos.bill')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='pos.qristransaction')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pos_qris_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['txn_ref', 'event'], name='pos_qris_au_txn_ref_62fe6b_idx'), models.Index(fields=['bill', 'created_at'], name='pos_qris_au_bill_id_8a0023_idx'), models.Index(fields=['event', 'created_at'], name='pos_qris_au_event_6d40c3_idx')],
            },
        ),
    ]
